const page = (id, title, summary, capabilities, steps, related = []) => ({
  id,
  title,
  summary,
  capabilities,
  steps,
  related,
});

export const DOC_SECTIONS = [
  {
    id: "get-started",
    label: "Get started",
    icon: "sparkle",
    pages: [
      page(
        "welcome",
        "Welcome to ASTRA",
        "Learn how ASTRA brings infrastructure, applications, telemetry, incidents, and business context into one operational workspace.",
        [
          "Understand the main product areas",
          "Choose the right collection path",
          "Move from telemetry to action",
        ],
        [
          "Review the core concepts",
          "Connect your first data source",
          "Verify that telemetry is arriving",
        ],
        ["quickstart", "concepts"],
      ),
      page(
        "quickstart",
        "ASTRA quickstart",
        "Use this path to connect data, confirm coverage, and create your first operational view.",
        [
          "Connect a supported source",
          "Validate collection health",
          "Explore entities and telemetry",
        ],
        [
          "Choose an integration",
          "Wait for the first accepted data",
          "Open the mapped workload",
          "Create a monitor or dashboard",
        ],
        ["welcome", "first-monitor"],
      ),
      page(
        "concepts",
        "Core concepts",
        "Understand organizations, projects, environments, entities, telemetry signals, monitors, and incidents.",
        [
          "Scope data by organization and project",
          "Navigate canonical entities",
          "Relate metrics, logs, traces, and events",
        ],
        [
          "Review your organization context",
          "Learn how entities are correlated",
          "Use time range and environment filters",
        ],
        ["welcome", "topology"],
      ),
    ],
  },
  {
    id: "collect-data",
    label: "Collect data",
    icon: "database",
    pages: [
      page(
        "overview",
        "Collect data",
        "Choose the collection path that matches your infrastructure and telemetry source.",
        [
          "Cloud integrations",
          "Linux Host Agent",
          "OpenTelemetry ingestion",
          "Kubernetes and RabbitMQ integrations",
        ],
        [
          "Choose a source",
          "Review permissions",
          "Connect the source",
          "Verify collection health",
        ],
        ["host-agent", "opentelemetry"],
      ),
      page(
        "aws",
        "Connect AWS",
        "Connect AWS accounts to discover cloud resources and collect supported AWS telemetry.",
        [
          "AWS resource inventory",
          "CloudWatch metrics and logs",
          "CloudTrail change context",
        ],
        [
          "Open Integrations → AWS",
          "Create the requested least-privilege access",
          "Choose accounts and regions",
          "Confirm collection health",
        ],
        ["collection-health", "topology"],
      ),
      page(
        "azure",
        "Connect Microsoft Azure",
        "Connect Azure subscriptions and bring supported resource context into ASTRA.",
        [
          "Subscription-scoped discovery",
          "Resource inventory",
          "Collection status",
        ],
        [
          "Open Integrations → Azure",
          "Provide the requested tenant and subscription access",
          "Save the connection",
          "Verify discovered resources",
        ],
        ["collection-health"],
      ),
      page(
        "gcp",
        "Connect Google Cloud",
        "Connect Google Cloud projects using the integration workflow and verify discovery.",
        [
          "Project-scoped collection",
          "Cloud resource inventory",
          "Connection health",
        ],
        [
          "Open Integrations → Google Cloud",
          "Configure the requested service account access",
          "Select projects",
          "Verify collection",
        ],
        ["collection-health"],
      ),
      page(
        "kubernetes",
        "Connect Kubernetes",
        "Connect a Kubernetes environment to surface cluster and workload context.",
        ["Cluster visibility", "Workload inventory", "Telemetry coverage"],
        [
          "Open Integrations → Kubernetes",
          "Follow the generated setup instructions",
          "Apply the required configuration",
          "Verify the cluster appears",
        ],
        ["collection-health", "workloads"],
      ),
      page(
        "host-agent",
        "Install the Linux Host Agent",
        "Install the ASTRA Agent on supported Linux hosts to collect host metrics and enabled logs, traces, and runtime evidence.",
        [
          "Host and process metrics",
          "File and journald logs when enabled",
          "Application Health and Docker signals when enabled",
        ],
        [
          "Generate an authorized installation command",
          "Run it on the intended Linux host",
          "Verify the service is healthy",
          "Confirm the canonical host appears",
        ],
        ["agent-configuration", "collection-health"],
      ),
      page(
        "opentelemetry",
        "Send OpenTelemetry data",
        "Send OTLP metrics, logs, and traces to the organization endpoint using authorized credentials.",
        [
          "OTLP/HTTP ingestion",
          "Organization-scoped authentication",
          "Resource and service correlation",
        ],
        [
          "Choose an OpenTelemetry SDK or Collector",
          "Configure the ASTRA OTLP endpoint",
          "Set the authorized API key securely",
          "Verify accepted records",
        ],
        ["metrics", "logs", "traces"],
      ),
      page(
        "rabbitmq",
        "Connect RabbitMQ",
        "Connect RabbitMQ monitoring and validate broker telemetry and collection state.",
        ["Broker visibility", "Queue and node context", "Integration health"],
        [
          "Open Integrations → RabbitMQ",
          "Enter the approved connection details",
          "Save and validate",
          "Review discovered broker data",
        ],
        ["collection-health"],
      ),
      page(
        "collection-health",
        "Verify collection health",
        "Use collection health to confirm source activity, accepted data, and actionable errors.",
        [
          "Connection status",
          "Last activity",
          "Collection errors",
          "Signal coverage",
        ],
        [
          "Select the connection",
          "Review recent activity",
          "Resolve authentication or permission errors",
          "Confirm new telemetry arrives",
        ],
        ["troubleshoot-collection"],
      ),
    ],
  },
  {
    id: "infrastructure",
    label: "Infrastructure",
    icon: "cloud",
    pages: [
      page(
        "overview",
        "Infrastructure overview",
        "Review the health and telemetry coverage of your connected infrastructure.",
        [
          "Cloud and host inventory",
          "Health and collection summaries",
          "Environment and project scoping",
        ],
        [
          "Choose the account and environment",
          "Review workload health",
          "Open an entity for details",
        ],
        ["workloads", "topology"],
      ),
      page(
        "workloads",
        "Explore workloads",
        "Browse every observed workload and understand which signals each one emits.",
        [
          "Live, stale, and inactive presence",
          "Metrics, logs, traces, and events coverage",
          "Canonical entity details",
        ],
        [
          "Set the time range",
          "Filter by cloud, collection source, project, or environment",
          "Select a workload",
          "Open its telemetry tabs",
        ],
        ["metrics", "logs"],
      ),
      page(
        "service-health",
        "Service health",
        "Check current resource state across connected accounts and narrow attention to unhealthy resources.",
        ["Resource health", "Status filters", "Recent observation time"],
        [
          "Choose a scope",
          "Filter unhealthy resources",
          "Open the affected entity",
          "Review related changes and telemetry",
        ],
        ["change-log", "monitors"],
      ),
      page(
        "databases",
        "Database monitoring",
        "Review supported database engines, collection coverage, and database recommendations.",
        [
          "Database inventory",
          "Engine measurements",
          "Coverage status",
          "Recommendations",
        ],
        [
          "Connect the database source",
          "Open Infrastructure → Databases",
          "Select an instance",
          "Review health and recommendations",
        ],
        ["metrics", "rabbitmq"],
      ),
      page(
        "topology",
        "Infrastructure topology",
        "Understand how cloud resources, hosts, services, and dependencies relate to one another.",
        [
          "Relationship map",
          "Canonical entity navigation",
          "Dependency and blast-radius context",
        ],
        [
          "Choose an environment",
          "Filter the topology",
          "Select an entity",
          "Follow related resources and services",
        ],
        ["workloads", "services"],
      ),
      page(
        "network",
        "Network visibility",
        "Review VPC traffic, data transfer context, reachability, and available network-log coverage.",
        [
          "Network flow context",
          "Transfer cost",
          "Reachability evidence",
          "Coverage state",
        ],
        [
          "Select a workload or network scope",
          "Review traffic and transfer",
          "Inspect reachability",
          "Follow the related entity",
        ],
        ["cost-attribution", "exposure"],
      ),
      page(
        "change-log",
        "Infrastructure change log",
        "See configuration changes recorded for monitored resources and compare them with health changes.",
        ["Configuration changes", "Affected resources", "Change timing"],
        [
          "Choose a time range",
          "Filter by workload",
          "Open a change",
          "Compare nearby monitor state changes",
        ],
        ["service-health", "incidents"],
      ),
      page(
        "exposure",
        "Internet exposure",
        "Understand what workloads expose publicly and review the evidence available to ASTRA.",
        ["Public endpoints", "Security-group context", "Per-workload exposure"],
        [
          "Choose a workload",
          "Review exposed ports and endpoints",
          "Validate intended access",
          "Investigate unexpected exposure",
        ],
        ["network", "workloads"],
      ),
    ],
  },
  {
    id: "applications",
    label: "Applications and services",
    icon: "cube",
    pages: [
      page(
        "overview",
        "Applications and services",
        "Understand service performance, dependencies, requests, errors, and user impact.",
        [
          "Service inventory",
          "APM health",
          "Dependency context",
          "Request and error analysis",
        ],
        [
          "Connect traces or supported Agent instrumentation",
          "Open the service inventory",
          "Select a service",
          "Investigate its signals",
        ],
        ["services", "requests"],
      ),
      page(
        "services",
        "Explore services",
        "Review detected services, versions, instances, deployment relationships, and recent activity.",
        [
          "Service health",
          "Versions and instances",
          "Deployed-on relationships",
          "Signal coverage",
        ],
        [
          "Choose an environment",
          "Select a service",
          "Review performance and dependencies",
          "Open related infrastructure",
        ],
        ["topology", "traces"],
      ),
      page(
        "requests",
        "Analyze requests",
        "Follow request behavior across services and identify slow or failing hops.",
        [
          "End-to-end request context",
          "Latency and error evidence",
          "Service and database hops",
        ],
        [
          "Select a service or workload",
          "Filter the request window",
          "Open a request",
          "Review each hop",
        ],
        ["traces", "errors"],
      ),
      page(
        "errors",
        "Investigate errors",
        "Explore application errors and recurring patterns from available telemetry.",
        ["Error groups", "Frequency and recency", "Related service context"],
        [
          "Set the time range",
          "Filter by service or environment",
          "Open an error group",
          "Compare logs and requests",
        ],
        ["logs", "requests"],
      ),
      page(
        "sessions",
        "Review user sessions",
        "Inspect supported real-user sessions, actions, page load behavior, and errors.",
        ["Session timeline", "User actions", "Load times", "Errors"],
        [
          "Choose a time window",
          "Filter sessions",
          "Open a session",
          "Review actions and related errors",
        ],
        ["errors", "monitors"],
      ),
    ],
  },
  {
    id: "telemetry",
    label: "Explore telemetry",
    icon: "chart",
    pages: [
      page(
        "metrics",
        "Explore metrics",
        "Search and visualize measurements associated with your infrastructure and services.",
        [
          "Metric discovery",
          "Time-series visualization",
          "Source and dimension filtering",
        ],
        [
          "Choose a time range",
          "Select an entity or metric",
          "Filter source and dimensions",
          "Compare series without double counting",
        ],
        ["dashboards", "monitors"],
      ),
      page(
        "logs",
        "Search logs",
        "Search logs across authorized scopes and preserve source, service, and infrastructure context.",
        [
          "Text and attribute search",
          "Source filtering",
          "Service and host association",
        ],
        [
          "Choose a time range",
          "Filter environment, source, host, or service",
          "Search records",
          "Open record details",
        ],
        ["errors", "log-reference"],
      ),
      page(
        "traces",
        "Explore traces",
        "Follow distributed requests across services and inspect spans, events, and dependencies.",
        [
          "Trace search",
          "Span timeline",
          "Service and infrastructure correlation",
        ],
        [
          "Choose a service or time range",
          "Filter trace attributes",
          "Open a trace",
          "Inspect the critical path",
        ],
        ["requests", "services"],
      ),
      page(
        "events",
        "Explore events",
        "Review operational and runtime events associated with canonical entities.",
        [
          "Lifecycle events",
          "Infrastructure context",
          "Event timing and attributes",
        ],
        [
          "Select an entity",
          "Choose the event window",
          "Filter event kind",
          "Open the supporting evidence",
        ],
        ["change-log", "incidents"],
      ),
    ],
  },
  {
    id: "monitoring",
    label: "Monitor and respond",
    icon: "bell",
    pages: [
      page(
        "triage",
        "Triage current issues",
        "Focus on what is failing now, what changed, and which entities need attention.",
        [
          "Current failures",
          "Affected resources",
          "Recent changes",
          "Investigation links",
        ],
        [
          "Open Monitors → Triage",
          "Review the highest-impact issue",
          "Inspect evidence",
          "Continue to an incident or entity",
        ],
        ["incidents", "change-log"],
      ),
      page(
        "monitors",
        "Create and manage monitors",
        "Define checks and thresholds for the signals your team relies on.",
        [
          "Metric and resource checks",
          "Thresholds",
          "Status history",
          "Notification routing",
        ],
        [
          "Choose the signal",
          "Define scope and threshold",
          "Set evaluation behavior",
          "Connect a notification channel",
        ],
        ["notification-overview", "first-monitor"],
      ),
      page(
        "incidents",
        "Investigate incidents",
        "Review incidents with affected entities, evidence, chronology, and proposed next steps.",
        [
          "Incident status",
          "Evidence timeline",
          "Affected entities",
          "ASTRA investigation context",
        ],
        [
          "Open an incident",
          "Review impact and evidence",
          "Validate relationships",
          "Track mitigation and recovery",
        ],
        ["triage", "astra-agents"],
      ),
      page(
        "synthetics",
        "Synthetic monitoring",
        "Schedule supported HTTP, TCP, and DNS probes to detect availability problems.",
        ["HTTP checks", "TCP checks", "DNS checks", "Probe history"],
        [
          "Choose a check type",
          "Enter the target and schedule",
          "Configure expected behavior",
          "Review probe results",
        ],
        ["monitors", "notification-overview"],
      ),
      page(
        "first-monitor",
        "Create your first monitor",
        "Create a focused monitor and route its notifications to the right responders.",
        [
          "Signal selection",
          "Scope and threshold",
          "Evaluation window",
          "Notifications",
        ],
        [
          "Open Monitors",
          "Create a monitor",
          "Choose the signal and threshold",
          "Save and verify its initial state",
        ],
        ["monitors", "notification-overview"],
      ),
    ],
  },
  {
    id: "dashboards-reports",
    label: "Dashboards and reports",
    icon: "gauge",
    pages: [
      page(
        "dashboards",
        "Build dashboards",
        "Create operational views from the metrics and context your team needs.",
        ["Reusable widgets", "Time and scope controls", "Saved dashboards"],
        [
          "Open Dashboards",
          "Create or open a dashboard",
          "Add widgets",
          "Save and share the view",
        ],
        ["metrics", "reports"],
      ),
      page(
        "manage-dashboards",
        "Manage dashboards",
        "Organize saved dashboards and maintain the views used by your teams.",
        ["Dashboard library", "Ownership and naming", "Saved configuration"],
        [
          "Open Manage dashboards",
          "Review existing boards",
          "Rename or update a board",
          "Remove obsolete boards carefully",
        ],
        ["dashboards"],
      ),
      page(
        "reports",
        "Use reports",
        "Browse operational and business reports generated from authorized platform data.",
        ["Operational summaries", "Business reporting", "Scoped time windows"],
        [
          "Open Reports",
          "Choose a report",
          "Set its scope and time range",
          "Review or export available results",
        ],
        ["unit-economics", "dashboards"],
      ),
    ],
  },
  {
    id: "notifications",
    label: "Notifications and workflows",
    icon: "flow",
    pages: [
      page(
        "notification-overview",
        "Notifications and workflows",
        "Connect communication and ITSM channels so monitor and incident updates reach responders.",
        [
          "Messaging channels",
          "Email and webhooks",
          "ITSM workflows",
          "Connection status",
        ],
        [
          "Choose a destination",
          "Authorize or configure it",
          "Send a test where available",
          "Attach it to the intended workflow",
        ],
        ["slack", "webhook"],
      ),
      page(
        "slack",
        "Connect Slack",
        "Route supported ASTRA notifications to approved Slack destinations.",
        [
          "Workspace connection",
          "Destination selection",
          "Notification delivery",
        ],
        [
          "Open Integrations → Slack",
          "Authorize the workspace",
          "Choose the approved destination",
          "Test and save",
        ],
        ["notification-overview"],
      ),
      page(
        "teams",
        "Connect Microsoft Teams",
        "Deliver supported notifications through the Microsoft Teams integration.",
        ["Teams connection", "Destination configuration", "Delivery status"],
        [
          "Open Integrations → Microsoft Teams",
          "Provide the requested authorization",
          "Choose the destination",
          "Test and save",
        ],
        ["notification-overview"],
      ),
      page(
        "email",
        "Configure email",
        "Send supported notifications to approved email recipients.",
        ["Recipient configuration", "Delivery routing", "Connection status"],
        [
          "Open Integrations → Email",
          "Add approved recipients",
          "Save the channel",
          "Attach it to the workflow",
        ],
        ["notification-overview"],
      ),
      page(
        "webhook",
        "Configure a webhook",
        "Send supported event payloads to an approved HTTPS endpoint.",
        ["HTTPS delivery", "Destination configuration", "Delivery status"],
        [
          "Open Integrations → Webhook",
          "Enter the approved HTTPS URL",
          "Configure authentication securely",
          "Test and save",
        ],
        ["notification-overview"],
      ),
      page(
        "servicenow",
        "Connect ServiceNow",
        "Connect supported ASTRA workflows to ServiceNow.",
        ["ITSM connection", "Workflow routing", "Delivery status"],
        [
          "Open Integrations → ServiceNow",
          "Authorize the instance",
          "Configure routing",
          "Test and save",
        ],
        ["notification-overview"],
      ),
      page(
        "jira",
        "Connect Jira",
        "Connect supported ASTRA workflows to Jira projects.",
        ["Jira connection", "Project routing", "Issue workflow"],
        [
          "Open Integrations → Jira",
          "Authorize the site",
          "Choose the project",
          "Test and save",
        ],
        ["notification-overview"],
      ),
    ],
  },
  {
    id: "costs",
    label: "Costs and optimization",
    icon: "wallet",
    pages: [
      page(
        "unit-economics",
        "Unit economics overview",
        "Relate infrastructure cost to customers, products, teams, and business units.",
        ["Cost summary", "Daily attribution", "Cost by business dimension"],
        [
          "Connect cost sources",
          "Configure ownership",
          "Review allocation coverage",
          "Explore unit cost",
        ],
        ["cost-attribution", "reports"],
      ),
      page(
        "cost-attribution",
        "Configure cost attribution",
        "Define how infrastructure spend is associated with the dimensions your business uses.",
        ["Ownership mapping", "Allocation rules", "Coverage validation"],
        [
          "Review unallocated cost",
          "Map resources to owners or products",
          "Add allocation rules",
          "Validate the result",
        ],
        ["unit-economics"],
      ),
      page(
        "optimization",
        "Find optimization opportunities",
        "Use available cost and utilization context to identify areas for review.",
        ["Cost trends", "Utilization context", "Resource-level evidence"],
        [
          "Choose a scope",
          "Review cost changes",
          "Compare supporting utilization",
          "Validate before acting",
        ],
        ["metrics", "unit-economics"],
      ),
    ],
  },
  {
    id: "astra-intelligence",
    label: "ASTRA Intelligence",
    icon: "brain",
    pages: [
      page(
        "astra-agents",
        "ASTRA agents",
        "Watch specialized ASTRA agents collaborate on incidents and investigations.",
        [
          "Agent activity",
          "Evidence and risks",
          "Proposed actions",
          "Audit context",
        ],
        [
          "Open ASTRA AI → Agents",
          "Choose an incident",
          "Review agent findings",
          "Validate suggested actions",
        ],
        ["analyzer", "incidents"],
      ),
      page(
        "analyzer",
        "ASTRA Analyzer",
        "Analyze workload health, cost, security, and operational posture in one view.",
        ["Multi-domain scoring", "Workload evidence", "Prioritized findings"],
        [
          "Open ASTRA Analyzer",
          "Choose a workload",
          "Review score drivers",
          "Open supporting evidence",
        ],
        ["workloads", "optimization"],
      ),
      page(
        "code",
        "ASTRA Code",
        "Investigate supported application errors and review proposed code-level changes.",
        ["Error context", "Code investigation", "Proposed changes"],
        [
          "Open ASTRA Code",
          "Select an error",
          "Review evidence and proposal",
          "Validate changes in your engineering workflow",
        ],
        ["errors", "requests"],
      ),
      page(
        "ask-astra",
        "Ask ASTRA",
        "Ask natural-language questions about authorized telemetry and operational context.",
        [
          "Natural-language exploration",
          "Scoped answers",
          "Links to supporting evidence",
        ],
        [
          "Open Ask ASTRA",
          "Set the right organization and environment scope",
          "Ask a focused question",
          "Open cited evidence",
        ],
        ["analyzer", "concepts"],
      ),
    ],
  },
  {
    id: "administration",
    label: "Administration",
    icon: "gear",
    pages: [
      page(
        "members",
        "Manage members",
        "Invite and manage organization members without weakening role boundaries.",
        ["Memberships", "Invitation status", "Account access"],
        [
          "Open Administration → Members",
          "Review the member",
          "Apply the intended membership action",
          "Confirm the result",
        ],
        ["roles", "sessions"],
      ),
      page(
        "roles",
        "Manage roles",
        "Assign permissions through organization roles and keep access aligned with responsibilities.",
        ["Role definitions", "Permission assignments", "Member-role mapping"],
        [
          "Review the required permissions",
          "Create or edit a role",
          "Assign members",
          "Verify access",
        ],
        ["permissions", "members"],
      ),
      page(
        "projects",
        "Manage projects",
        "Use projects to organize and scope supported platform resources.",
        ["Project definitions", "Organization ownership", "Scoped views"],
        [
          "Open Administration → Projects",
          "Create or select a project",
          "Configure its details",
          "Use it in product filters",
        ],
        ["concepts"],
      ),
      page(
        "plan",
        "View your plan",
        "Review the organization plan, availability window, and current status.",
        ["Current plan", "Start and expiry time", "Plan status"],
        [
          "Open Administration → Plan",
          "Review current status",
          "Contact the authorized administrator for plan changes",
        ],
        ["members"],
      ),
      page(
        "audit",
        "Review organization audit activity",
        "Review administrative actions recorded for your organization.",
        ["Actor and action", "Target context", "Result and time"],
        [
          "Open Administration → Audit",
          "Set the time range",
          "Filter the activity",
          "Expand details when needed",
        ],
        ["sessions"],
      ),
      page(
        "sessions",
        "Manage sessions",
        "Review and revoke supported organization sessions when access should end.",
        ["Session inventory", "Activity time", "Revocation"],
        [
          "Open Administration → Sessions",
          "Review the user and activity",
          "Revoke the intended session",
          "Confirm it is no longer active",
        ],
        ["members", "audit"],
      ),
    ],
  },
  {
    id: "reference",
    label: "Reference",
    icon: "book",
    pages: [
      page(
        "agent-configuration",
        "Host Agent configuration reference",
        "Understand the supported customer configuration areas for the Linux Host Agent.",
        [
          "Observe endpoint and authorization",
          "Metrics, logs, traces, and Application Health capabilities",
          "Durable state and queue settings",
        ],
        [
          "Start from the packaged YAML template",
          "Enable only required capabilities",
          "Run the configuration check",
          "Restart and verify the service",
        ],
        ["host-agent", "troubleshoot-collection"],
      ),
      page(
        "api-reference",
        "API and ingestion reference",
        "Review customer-facing endpoints and authentication requirements exposed by ASTRA.",
        [
          "Authorized API access",
          "OTLP ingestion paths",
          "Error and retry behavior",
        ],
        [
          "Choose the supported API",
          "Use organization-scoped credentials",
          "Handle errors without exposing secrets",
        ],
        ["opentelemetry", "permissions"],
      ),
      page(
        "permissions",
        "Permissions reference",
        "Understand the permission groups used by customer-facing ASTRA areas.",
        [
          "Read and manage permissions",
          "Integration-specific permissions",
          "Organization role assignment",
        ],
        [
          "Identify the required product action",
          "Find its permission",
          "Assign through the intended role",
          "Verify least-privilege access",
        ],
        ["roles"],
      ),
      page(
        "log-reference",
        "Log attributes reference",
        "Understand the common service, host, cloud, source, and provenance fields available in Logs.",
        [
          "Service identity",
          "Canonical host identity",
          "Cloud context",
          "Source provenance",
        ],
        [
          "Open a log record",
          "Review resource and record attributes",
          "Use bounded filters",
          "Follow the associated entity",
        ],
        ["logs", "host-agent"],
      ),
      page(
        "glossary",
        "ASTRA glossary",
        "Find definitions for the entities, telemetry signals, scopes, and operational terms used throughout ASTRA.",
        [
          "Canonical entity",
          "Workload and service",
          "Collection source",
          "Monitor and incident",
        ],
        [
          "Search for a term",
          "Open the related guide",
          "Apply the concept in the product",
        ],
        ["concepts"],
      ),
    ],
  },
  {
    id: "troubleshooting",
    label: "Troubleshooting",
    icon: "lifebuoy",
    pages: [
      page(
        "troubleshoot-collection",
        "Troubleshoot collection",
        "Resolve missing or stale telemetry by checking source status, permissions, and recent activity.",
        [
          "Collection health",
          "Authentication status",
          "Last activity",
          "Signal-specific errors",
        ],
        [
          "Open collection health",
          "Select the source",
          "Read the actionable error",
          "Correct access and verify new data",
        ],
        ["collection-health", "missing-telemetry"],
      ),
      page(
        "authentication",
        "Troubleshoot sign-in and access",
        "Resolve common customer sign-in, organization membership, and permission problems.",
        ["Active organization membership", "Role permissions", "Session state"],
        [
          "Confirm the organization is active",
          "Verify membership",
          "Review role permissions",
          "Sign in again after access changes",
        ],
        ["members", "roles"],
      ),
      page(
        "missing-telemetry",
        "Troubleshoot missing telemetry",
        "Narrow missing data by signal, source, entity, scope, and time range.",
        [
          "Metrics, logs, and traces coverage",
          "Time range and environment scope",
          "Source provenance",
        ],
        [
          "Confirm the expected signal is enabled",
          "Review collection health",
          "Check filters and time range",
          "Open the canonical entity",
        ],
        ["metrics", "logs", "traces"],
      ),
      page(
        "agent-service",
        "Troubleshoot the Linux Host Agent",
        "Check configuration, service health, permissions, and durable delivery state without exposing credentials.",
        [
          "Configuration validation",
          "systemd status",
          "Journal diagnostics",
          "Queue activity",
        ],
        [
          "Run the Agent configuration check",
          "Review systemctl status",
          "Review redacted journal diagnostics",
          "Confirm outbound HTTPS reachability",
        ],
        ["agent-configuration", "host-agent"],
      ),
    ],
  },
  {
    id: "whats-new",
    label: "What's new",
    icon: "newspaper",
    pages: [
      page(
        "release-notes",
        "ASTRA release notes",
        "Review customer-visible improvements across collection, infrastructure, applications, monitoring, and administration.",
        ["Product improvements", "New integrations", "Behavior changes"],
        [
          "Choose a release",
          "Review affected areas",
          "Follow linked migration or setup guidance when applicable",
        ],
        ["latest-docs"],
      ),
      page(
        "latest-docs",
        "Documentation updates",
        "See recently added and substantially revised customer documentation.",
        [
          "New guides",
          "Updated reference pages",
          "Troubleshooting improvements",
        ],
        [
          "Review recent updates",
          "Open the changed guide",
          "Share relevant guidance with your team",
        ],
        ["release-notes"],
      ),
    ],
  },
];

export const ALL_PAGES = DOC_SECTIONS.flatMap((section) =>
  section.pages.map((item) => ({
    ...item,
    sectionId: section.id,
    sectionLabel: section.label,
  })),
);

export function findPage(sectionId, pageId) {
  const section = DOC_SECTIONS.find((item) => item.id === sectionId);
  const item = section?.pages.find((entry) => entry.id === pageId);
  return section && item ? { section, page: item } : null;
}

export function findPageById(pageId) {
  return ALL_PAGES.find((item) => item.id === pageId) || null;
}
