import { HANDBOOK, readingTime } from './handbookContent.js';
import { PRODUCT_SCREENS } from './productScreenshots.js';
// Customer guidance is authored separately from navigation; no credentials or deployment runbooks.
export const GROUPS = [
  { label: 'Essentials', ids: ['get-started', 'collect-data'] },
  { label: 'Observe and investigate', ids: ['infrastructure', 'applications', 'telemetry'] },
  { label: 'Operate and improve', ids: ['monitoring', 'dashboards-reports', 'notifications', 'costs', 'astra-intelligence'] },
  { label: 'Manage and learn', ids: ['administration', 'reference', 'troubleshooting', 'whats-new'] },
];

const section = (id, title, blocks) => ({ id, title, blocks });
const text = (value) => ({ type: 'text', value });
const list = (...items) => ({ type: 'list', items });
const table = (headers, rows) => ({ type: 'table', headers, rows });
const note = (title, value) => ({ type: 'note', title, value });
const steps = (...items) => ({ type: 'steps', items });
const screenshot = (title) => ({ type: 'image', src: '/guides/workload-metrics.png', title: 'ASTRA workload inventory and scope filters', caption: 'Actual local ASTRA workload inventory with no matching workloads in the selected window. Account details are redacted. No telemetry has been fabricated.' });

export const GUIDES = {
  'notifications/email': {
    type: 'Connection guide', time: '6 min', sections: [
      section('prepare-email', 'Before you connect SMTP', [text('Connect an Email channel to deliver monitor state changes to your team. Obtain SMTP settings from your mail administrator before opening the form.'), list('SMTP hostname, port, and TLS mode.', 'An authorized sender address and recipient addresses.', 'Username and password or app password, if required by your mail provider.', 'Permission to manage notification channels in the current organization.'), note('Access required', 'The Add Email action requires integrations.channels.manage. If it is unavailable, ask your organization administrator to review your role.')]),
      section('open-email', 'Open the Email integration', [steps(['Open Integrations', 'Select Email from the integration catalogue.'], ['Select + Add Email', 'The Connect Email form opens below the channel list.'], ['Name the channel', 'Use a recognizable display name such as Production on-call.']) , {type:'image',src:'/guides/email-setup.png',title:'Email channel setup in ASTRA',caption:'Connect Email form captured from the local ASTRA application. Account details are redacted; no credentials are entered.'}]),
      section('smtp-fields', 'Enter your SMTP settings', [table(['Field', 'What to enter'], [['SMTP host', 'The hostname supplied by your mail provider.'], ['Port', 'The SMTP port required by your provider. The form shows 587 as an example.'], ['Implicit TLS (port 465)', 'Enable only when your provider requires implicit TLS, typically on port 465.'], ['Username', 'Your authorized SMTP account, if authentication is required.'], ['Password / app password', 'The credential supplied for that SMTP account. Never share it in screenshots.'], ['From address', 'A sender address the SMTP account is permitted to use.'], ['Recipients', 'One or more recipient email addresses, separated by commas.']]), note('Use provider-approved settings', 'Do not guess TLS settings or reuse your personal account password. Your provider may require an app password or a dedicated service account.')]),
      section('events', 'Choose when the channel receives notifications', [text('Select Critical, Warning, and/or Recovered for monitor state changes. Matching events are delivered to enabled channels. Review your choices to avoid notifying the wrong audience.'), text('Save the channel after reviewing the sender, recipients, and event selection.')]),
      section('test-delivery', 'Test and verify delivery', [steps(['Select Test on the saved channel', 'This sends a real test notification. Use approved recipients.'], ['Check the receiving mailbox', 'Confirm receipt, including spam or quarantine handling.'], ['Review Last test and Deliveries', 'Last test shows the most recent result. Deliveries shows ASTRA’s recorded send attempts.']), note('A send result is not inbox confirmation', 'Mail filtering and downstream delivery can still affect receipt. Confirm that the intended recipient sees the message.')]),
      section('email-troubleshoot', 'Resolve common setup issues', [{type:'accordion',items:[['Authentication failed','Check the SMTP username and whether your provider requires an app password. Review provider restrictions before retrying.'],['Connection or TLS failure','Verify the SMTP hostname, port, TLS mode, and outbound connectivity from the platform. Ask the platform operator to investigate connectivity; do not disable certificate validation.'],['The test succeeds but email is absent','Check recipients, spam/quarantine rules, sender authorization, and mail-provider delivery logs.'],['How do I stop notifications?','Disable the channel to stop new automatic deliveries. In-progress sends may finish. You can re-enable it later without deleting the configuration.']]}]),
    ],
  },
  'get-started/quickstart': {
    type: 'Quickstart', time: '6 min', sections: [
      section('before-you-begin', 'Before you begin', [text('Start with one system and one question: is the system healthy, and can you investigate a change? You do not need to connect every source before ASTRA becomes useful.'), list('Select the organization that should own the data.', 'Have permission to manage the integration you want to connect.', 'Choose a host or cloud account that you are authorized to monitor.'), note('Already connected?', 'Skip collection setup and open Clouds → Workloads. Choose a recently observed workload to begin exploring.')]),
      section('connect', 'Get your first data flowing', [{ type: 'tabs', tabs: [
        { title: 'Linux host', text: 'Open Integrations → Host agents. Generate an authorized key and use the installation command shown by your own platform. Run it on the intended Linux host. Keep the key private.', next: 'A host appears after its first accepted telemetry batch. A running service alone does not prove delivery.' },
        { title: 'Cloud account', text: 'Open Integrations and select AWS, Microsoft Azure, or Google Cloud. Follow that provider’s connection flow and review the requested permissions before authorizing access.', next: 'Wait for discovery and collection. Check the connection state and the timestamp of the newest observation.' },
        { title: 'OpenTelemetry', text: 'Choose OpenTelemetry when your application already exports telemetry. Use the endpoint and authentication instructions supplied for your organization.', next: 'Check each signal independently. Receiving metrics does not imply that logs or traces are configured.' },
      ] }]),
      section('explore', 'Open a workload and inspect its evidence', [text('Open Clouds → Workloads and select the observed entity. Start with a recent time window. The signal tabs show what was actually received for this workload.'), screenshot('Read the workload metrics view'), table(['Signal', 'What to look for'], [['Metrics', 'Recent samples, units, source, and the selected time range.'], ['Logs', 'Record timestamps, severity, body, and source attributes.'], ['Traces', 'Instrumented requests and spans associated with the workload.'], ['Events', 'Observed changes and runtime evidence when enabled.']]), note('No samples is a useful state', 'An empty tab means there is no matching evidence in this scope and time window. It does not establish that the system is healthy or broken.')]),
      section('investigate', 'Follow a question through the data', [steps(['Choose a symptom', 'For example, find the time when CPU usage increased or requests became slower.'], ['Keep the same time window', 'Use a consistent interval when comparing metrics, logs, and traces.'], ['Check the source', 'Agent and cloud-provider measurements can use different intervals and definitions.'], ['Record what you know', 'Separate observed evidence from your hypothesis before changing the system.'])]),
      section('next-steps', 'Build your next operational view', [text('Use a dashboard for a repeated question and a monitor for a condition that needs attention. Start narrowly, confirm the data is available, and then expand coverage.'), { type: 'links', ids: ['metrics', 'logs', 'first-monitor', 'dashboards'] }]),
    ],
  },
  'telemetry/metrics': {
    type: 'Explorer guide', time: '5 min', sections: [
      section('choose-scope', 'Start with an entity and a time window', [text('Open Observability → Metrics. Select Scope, Workload, and a time range. Choose a metric from Agent metrics or Agentless metrics. Use Aggregation, Resolution, and Group by to control how available measurements are presented.'), {type:'image',src:'/guides/metrics.png',title:'ASTRA Metrics Explorer controls',caption:'Actual Metrics Explorer capture with no measurements in the selected scope. Account details are redacted.'}]),
      section('sources', 'Understand where a measurement comes from', [table(['Source', 'Useful for', 'Interpretation'], [['Agent / OTLP', 'Host and application measurements emitted by an installed collector or instrumented application.', 'Check units and attributes; not every metric is available on every host.'], ['AWS / CloudWatch', 'Measurements collected through the AWS integration.', 'CloudWatch periods and dimensions may differ from Agent measurements.']]), note('Avoid double counting', 'Two measurements with similar names are not automatically interchangeable. Keep source provenance visible when comparing them; do not add duplicate measurements of the same quantity.')]),
      section('read-series', 'Read the series before drawing a conclusion', [steps(['Inspect the metric name and unit', 'A percentage, byte count, rate, and cumulative counter answer different questions.'], ['Review dimensions', 'CPU state, network interface, disk device, and filesystem mountpoint can produce multiple series.'], ['Compare like with like', 'Use the same entity, time range, unit, and aggregation when comparing intervals.'])]),
      section('empty-metrics', 'When a metric is missing', [{ type: 'accordion', items: [['The entity exists but has no recent samples', 'Discovery and telemetry collection are separate. Widen the time range and check collection health before concluding that the entity is no longer running.'], ['Memory or filesystem measurements are absent', 'These measurements require a collector that emits them. A cloud integration alone may not provide the same coverage as an installed host Agent.'], ['Values differ between sources', 'Check sampling period, units, dimensions, and aggregation. A difference does not by itself mean one source is incorrect.']] }]),
    ],
  },
  'telemetry/logs': {
    type: 'Investigation guide', time: '5 min', sections: [
      section('find-records', 'Find the records around a symptom', [text('Logs provide individual records with timestamps and context. Begin with the organization, workload, and time interval involved in the incident. Narrow the result only after you have confirmed that data is present.'), steps(['Choose a time window', 'Include a short period before and after the reported symptom.'], ['Set the workload or service scope', 'A host-level record and an application record may be associated differently.'], ['Inspect a record', 'Read its timestamp, severity, source, and attributes before following a related entity.'])]),
      section('log-sources', 'Know which source you are searching', [text('Open Observability → Logs. The current view provides Severity, Source, Region, Log group, and Log stream filters. Clear filters resets these selections; widen the window when no records match.'), {type:'image',src:'/guides/logs.png',title:'ASTRA Logs filters and empty state',caption:'Actual Logs view with no matching records. Account details are redacted; no log bodies are exposed.'}, table(['Source', 'Typical records', 'Collection requirement'], [['Linux file logs', 'Application or system files selected for collection.', 'Explicit source configuration and read permission.'], ['Journald', 'Systemd journal entries.', 'Journal collection enabled and journal access granted.'], ['Docker logs', 'Container stdout and stderr.', 'Docker log collection enabled with approved runtime access.'], ['OTLP', 'Logs exported by instrumentation or a collector.', 'Correct endpoint and organization authentication.'], ['CloudWatch', 'AWS log records from configured collection.', 'Cloud integration and relevant collection permissions.']]), note('Protect sensitive content', 'Log bodies may contain customer or application data. Review your collection policy before enabling a source and avoid including secrets in shared screenshots or exported examples.')]),
      section('correlate', 'Move from a record to the affected entity', [text('Use the associated entity and resource attributes to keep the investigation in context. A service name identifies application context; host identity identifies infrastructure. A record’s text alone is not reliable proof of its host association.')]),
      section('no-results', 'Troubleshoot an empty result', [{ type: 'accordion', items: [['Metrics arrive, but logs do not', 'Signals are configured independently. Confirm the intended log source is enabled, producing new records, and readable by the collector.'], ['The same time range works in another view', 'Check organization, source, workload, and service filters. Remove one filter at a time to identify the mismatch.'], ['Records arrive late', 'Compare the event timestamp with the arrival time and check collector delivery health. A recovered queue can deliver older records.']] }]),
    ],
  },
  'collect-data/host-agent': {
    type: 'Installation guide', time: '7 min', sections: [
      section('requirements', 'Check the host and your access', [list('Use a supported Linux host and review the installation options presented by your platform.', 'Use a key authorized for the organization that should receive the data.', 'Ensure the host can reach the HTTPS endpoint shown in the installer.', 'Have operator permission to install and manage the host service.'), note('Use your platform’s command', 'Copy the current command from Integrations → Host agents. Do not reuse a command or credential from another organization or documentation screenshot.')]),
      section('install', 'Install from Integrations → Host agents', [steps(['Select your organization', 'Confirm the customer organization before generating an Agent key.'], ['Choose collection options', 'Review which signals are enabled and which additional permissions they need.'], ['Run the generated command', 'Use the exact endpoint provided by your platform. Keep the key out of shared terminal history and screenshots.'], ['Wait for the first accepted batch', 'Confirm that the host appears and its last-observed time advances.'])]),
      section('coverage', 'Verify each signal independently', [table(['Signal', 'Evidence of collection'], [['Host metrics', 'Recent measurements on the mapped workload.'], ['File logs', 'New records from explicitly configured, readable files.'], ['Journal logs', 'New records from journal sources allowed to the service account.'], ['Application Health', 'Process, systemd, or health-check evidence from configured observations.'], ['Docker', 'Container evidence only when enabled and runtime access is provisioned.']])]),
      section('verify-host', 'Find the installed host', [screenshot('Inspect the host after its first telemetry arrives'), text('Use the mapped workload to inspect operational telemetry. Use the Host agents integration to check installation and reporting state. A collector may report metrics successfully while another optional source needs attention.')]),
      section('agent-help', 'If the host does not report', [{ type: 'accordion', items: [['No host appears', 'Check service status, endpoint reachability, and whether the key is authorized for this organization. Do not paste the key into a support conversation.'], ['The host is present but stale', 'Check its most recent observation and the selected time window. Review local delivery status before reinstalling.'], ['Only some logs are missing', 'Check the configured source and service-account permissions. Do not broadly weaken host permissions to make a source readable.']] }]),
    ],
  },
  'get-started/concepts': {
    type: 'Concepts', time: '4 min', sections: [
      section('scope', 'Organization, project, and environment', [text('An organization is the access and data boundary for your workspace. Projects and environments add context within that boundary. Check these selections before comparing two views or sharing an investigation.'), table(['Concept', 'Question it answers'], [['Organization', 'Whose data and permissions are being used?'], ['Project', 'Which team or application context am I investigating?'], ['Environment', 'Is this production, staging, development, or unassigned?']])]),
      section('entities', 'Entities provide a common investigation context', [text('An entity represents an observed resource such as a host, service, or cloud resource. Multiple telemetry sources can describe the same resource. Use the associated entity and source metadata to interpret those observations.'), note('A name is not an identity', 'Hostnames, IP addresses, and image names can change or be reused. Treat them as descriptive context rather than proof that two observations describe the same resource.')]),
      section('signals', 'Four complementary kinds of evidence', [table(['Signal', 'Best starting question'], [['Metrics', 'What changed, by how much, and when?'], ['Logs', 'What did the system record around that moment?'], ['Traces', 'Where did a request spend time or encounter an error?'], ['Events', 'Which observed lifecycle or configuration changes occurred?']])]),
      section('actions', 'From observation to action', [text('Use monitors to evaluate defined conditions and incidents to organize a response. Dashboards retain a useful view of measurements. None of these replaces verifying the underlying source and time window.')]),
    ],
  },
  'infrastructure/workloads': {
    type: 'Product guide', time: '5 min', sections: [
      section('inventory', 'Choose the workload you want to understand', [text('The workload inventory brings observed systems into a common view. Narrow the inventory with the available scope and time filters, then select a workload to inspect its evidence.'), screenshot('Workload detail and its telemetry tabs')]),
      section('evidence', 'Read telemetry coverage', [table(['View', 'What it tells you'], [['Overview / Properties', 'Resource context and descriptive attributes.'], ['Metrics', 'Available measurements and their samples.'], ['Logs', 'Matching records in the current scope.'], ['Traces', 'Request evidence when instrumentation is present.'], ['Events', 'Observed changes when the source emits them.']]), note('Presence is not health', 'Recently observed telemetry proves that evidence arrived. It does not guarantee that every application on the host is healthy.')]),
      section('investigation', 'Investigate without losing context', [steps(['Confirm the entity', 'Check the resource identity and cloud context where available.'], ['Set the incident window', 'Keep the same time range while changing signal tabs.'], ['Follow related evidence', 'Use service or topology relationships as investigation context and verify the relevant observations.'])]),
    ],
  },
  'troubleshooting/missing-telemetry': {
    type: 'Troubleshooting', time: '4 min', sections: [
      section('symptom', 'Identify what is missing', [text('Start by separating a missing entity, an empty signal, and stale data. These point to different checks. Avoid reinstalling a collector until you know which boundary is failing.')]),
      section('diagnose', 'Choose your symptom', [{ type: 'tabs', tabs: [
        { title: 'No entity', text: 'Verify the selected organization and the connection or Agent reporting state. Confirm at least one batch has been accepted.', next: 'Check access scope before assuming discovery failed.' },
        { title: 'Empty signal', text: 'Confirm the signal is enabled at the source. Metrics, logs, and traces have independent collection requirements.', next: 'Remove restrictive filters and widen the time window.' },
        { title: 'Stale data', text: 'Compare the newest observation with the source clock and review delivery errors or local backlog.', next: 'After recovery, verify that new observations advance rather than only replaying older records.' },
      ] }]),
      section('checks', 'Check the collection path', [steps(['Source', 'Is the application producing the expected signal?'], ['Collector', 'Is that source configured, readable, and observed?'], ['Delivery', 'Is the endpoint reachable and authentication accepted?'], ['View', 'Does the selected organization, entity, and time window include the data?'])]),
      section('support', 'Prepare a useful support report', [list('Affected signal and approximate UTC time window.', 'Collector version and sanitized error category.', 'Whether other signals or sources are reporting.', 'Filters used in the view.'), note('Keep credentials private', 'Do not attach API keys, raw configuration secrets, or unreviewed application log bodies.')]),
    ],
  },
};

const CHANNELS = {
  slack: {name:'Slack',prepare:'Create an incoming webhook for your intended Slack channel using an approved Slack app. Copy the webhook URL privately.',fields:[['Incoming webhook URL','The secret URL from Slack app → Incoming Webhooks → Add to workspace.']],verify:'Confirm the test message in the intended Slack channel.'},
  teams: {name:'Microsoft Teams',prepare:'In the intended Teams channel, use Workflows with “When a Teams webhook request is received” and a step that posts an Adaptive Card. The current integration expects the trigger authentication to be “Anyone”. Check your organization policy before using that setting and maintain a workflow owner and co-owner.',fields:[['Teams Workflow webhook URL','The HTTPS URL generated by the approved workflow. Treat it as a secret.']],verify:'Confirm the test card in Teams and check Workflow run history. A webhook acceptance alone does not prove a channel post.'},
  webhook: {name:'Webhook',prepare:'Prepare an approved HTTPS receiver for alert JSON. Obtain its bearer token if the receiving endpoint requires one.',fields:[['Endpoint URL','The receiving HTTPS endpoint.'],['Bearer token (optional)','The credential expected by the receiver, when required.']],verify:'Confirm the receiving system accepted and processed the test request.'},
  servicenow: {name:'ServiceNow',prepare:'Prepare a dedicated integration user with the permissions approved for your ServiceNow instance.',fields:[['Instance URL','The ServiceNow instance address.'],['Integration user','The dedicated integration username.'],['Password','The integration account credential.'],['Assignment group (optional)','The group name or sys_id.'],['Caller (optional)','The caller sys_id, where required by your workflow.']],verify:'Inspect the test result and the intended ServiceNow instance. Review assignment and caller handling before enabling broad notifications.'},
  jira: {name:'Jira',prepare:'Prepare an authorized Jira account, API token, and destination project. Confirm which issue type and completion transition your project uses.',fields:[['Site URL','The Jira site address.'],['Account email','The account authorized for the project.'],['API token','The account API token.'],['Project key','The target project key.'],['Issue type','The issue type configured for the project.'],['Labels (optional)','Labels to attach to created issues.'],['Done transition','The exact transition name or target status used to close the ticket.'],['Priority for critical (optional)','The Jira priority name to use for critical incidents.']],verify:'Verify the target project and resulting ticket behavior before relying on automatic incident updates.'},
};
for (const [id,channel] of Object.entries(CHANNELS)) {
  GUIDES[`notifications/${id}`]={type:'Connection guide',time:'5 min',sections:[
    section('prerequisites','Prepare the connection',[text(channel.prepare),note('Required access','Use an account with integrations.channels.manage in the correct organization. Credentials and webhook URLs must stay private.')]),
    section('connect',`Connect ${channel.name}`,[steps(['Open Integrations',`Select ${channel.name} in the catalogue.`],[`Select + Add ${channel.name}`,'Enter a recognizable display name for this channel.'],['Configure the destination','Fill in the fields below using values approved by your integration administrator.']),{type:'image',src:`/guides/${id}-setup.png`,title:`${channel.name} connection form`,caption:'Actual ASTRA connection form. Existing account and connection details are redacted; secret fields are empty.'}]),
    section('fields','Connection fields',[table(['Field','Value'],channel.fields)]),
    section('delivery','Choose events and verify delivery',[text('Choose Critical, Warning, and/or Recovered under Send on, then select Create channel. These checkboxes apply to monitor state changes.'),steps(['Run an approved Test','The Test action sends a real request to the configured destination.'],['Confirm receipt',channel.verify],['Inspect Deliveries','Review the recorded attempts and use Last test to check the most recent result.']),note('Disabling a channel','Disable stops new automatic deliveries. In-progress sends may finish; existing tickets or external messages are not removed.')]),
    section('troubleshoot','If the test fails',[{type:'accordion',items:[['Authentication or permission error','Review the integration credential, its destination permissions, and any provider restrictions. Do not share the secret while troubleshooting.'],['Delivery accepted but nothing appears',channel.verify],['Editing an existing secret','Secret fields are not echoed back. Leave them blank when editing to retain the current secret, or supply an approved replacement.']]}]),
  ]};
}
GUIDES['collect-data/overview']={type:'Overview',time:'4 min',sections:[
  section('choose','Choose a collection path',[text('Open Integrations to browse the catalogue. Search by product or use the category filters. Your connections shows configured integrations; Available integrations shows the choices your role can access.'),{type:'image',src:'/guides/integrations.png',title:'ASTRA integration catalogue',caption:'Actual integration catalogue. Existing connection and account names are redacted.'}]),
  section('compare','Which path fits your system?',[table(['Path','Choose it when'],[['Cloud integration','You need cloud inventory and provider telemetry.'],['Host agents','You need measurements and enabled logs from Linux machines.'],['OpenTelemetry','Your application or collector already exports OTLP.'],['Databases / RabbitMQ','You need supported engine or broker collection.']])]),
  section('guides','Connection guides',[{type:'directory',sectionId:'collect-data'}]),
]};

const CONTEXT = {
  'notifications/email': ['Why use email for operational notifications?', 'Email is useful when responders already work through a maintained mailbox or distribution list. The important choice is not only the SMTP server: it is who receives the message, which changes deserve attention, and what the recipient is expected to do next.', 'Keep sender authentication separate from delivery confirmation. A valid SMTP account can submit a message that is later filtered or sent to the wrong audience. Use an approved test recipient and verify receipt before relying on the channel for an incident.'],
  'get-started/quickstart': ['What this quickstart establishes', 'The goal is a small, verified chain of evidence: one source produces telemetry, ASTRA receives it in the intended organization, and you can inspect it in a useful view. It is not necessary to configure every integration or signal at once.', 'Choose a question first. For host resource pressure, begin with host measurements. For a failed request, instrument the application. This prevents a successful installation from being mistaken for complete observability. At the end, you should know what is collected, where to find it, and what remains unconfigured.'],
  'telemetry/metrics': ['What a metric can explain', 'A metric is a measurement with a time, unit, and dimensions. It can tell you how a system changes and help distinguish a brief spike from sustained pressure. It cannot, on its own, explain every cause of that change.', 'Consider CPU usage during an incident. A high value is a reason to compare workload demand and application behavior, not an automatic instruction to add capacity. A percentage, count, rate, and cumulative counter each need a different interpretation. Check what the displayed series represents before deciding whether it is abnormal.'],
  'telemetry/logs': ['Why logs are useful during an investigation', 'Logs can preserve the words and context recorded by a system near a symptom. They help answer what the application reported, which operation it was performing, and whether a pattern repeated. They complement metrics rather than replacing them: a graph can identify when behavior changed, while a relevant record can explain what was observed at that moment.', 'Do not begin by searching only for the word error. Some useful records have informational severity, while a severe message may describe an expected retry. Narrow the time and source, inspect representative records, and then build a more specific search from the attributes that actually exist.'],
  'collect-data/host-agent': ['When a host Agent is the right collection path', 'The Linux Host Agent collects supported evidence from the machine where it runs. It is useful when you need host measurements or explicitly enabled local sources that a cloud inventory connection cannot provide. Optional capabilities have their own configuration and permission requirements.', 'A host collector and application instrumentation solve different problems. Host CPU and memory can explain resource pressure, but request traces require a supported trace-producing path. Decide which signals you need and verify each one after installation instead of treating the host appearing in inventory as proof of every capability.'],
  'get-started/concepts': ['Why these distinctions matter', 'Operational mistakes often begin by treating different objects as equivalent: a host becomes a service, an alert becomes a cause, or a missing value becomes zero. ASTRA keeps resource identity, application context, and observed signals distinct so investigations can stay grounded in evidence.', 'For an illustrative checkout failure, the service identifies the application responsibility, a trace describes one instrumented request, and the host supplies infrastructure context. A monitor may detect a condition, while an incident organizes the response. Knowing which question each object answers makes it easier to choose the next view.'],
  'infrastructure/workloads': ['Use a workload as an evidence hub', 'Workloads provides a common entry point for understanding an observed system. Instead of searching for the same host separately in every signal view, inspect the resource context and then move between the evidence available for it.', 'This is especially useful when names repeat or multiple sources describe the same system. Confirm identity and source context before interpreting a metric or log as belonging to the selected workload. A listed workload with sparse telemetry is a coverage question, not automatically a healthy or unhealthy verdict.'],
  'troubleshooting/missing-telemetry': ['Why restarting is not the first check', 'An empty view can be produced by a disabled source, unreadable file, rejected key, wrong organization, restrictive filter, or time window that excludes the records. Restarting changes only some of those conditions and can distract from the actual boundary.', 'Use one expected record or measurement as your test case. Establish where it should originate, which collector should observe it, and which platform scope should contain it. Then move through those boundaries in order, preserving delivery state and changing one factor at a time.'],
  'collect-data/overview': ['Collection should follow the question you need to answer', 'Different collection paths provide different evidence. Cloud integrations discover provider resources and supported telemetry. A host Agent observes supported local sources. Application instrumentation creates request-level context. These can complement each other without being substitutes.', 'For example, a cloud account connection may identify the machine running a service but not supply that service’s request spans. Before connecting another source, check whether it provides the missing signal and whether you can authorize its access safely. Verify coverage after setup rather than inferring it from the catalogue.'],
};
for (const [key, [title, ...paragraphs]] of Object.entries(CONTEXT)) {
  GUIDES[key].sections.unshift(section('why-this-guide', title, paragraphs.map(text)));
}
for (const [id, channel] of Object.entries(CHANNELS)) {
  const purpose = {
    slack: 'Use Slack when a maintained team channel is the place where responders coordinate. A notification should identify the condition and support a handoff; posting to several channels without ownership can create more noise than clarity.',
    teams: 'Use Teams when responders coordinate through a maintained team workflow. A workflow has its own ownership and delivery behavior, so a platform send result and an actual channel post must be verified separately.',
    webhook: 'Use a webhook when an approved receiving system needs supported alert payloads rather than a human-readable mailbox message. The receiver must interpret the payload safely and handle its own downstream processing.',
    servicenow: 'Use ServiceNow when the response process depends on ticket ownership and an established service-management workflow. Confirm assignment and caller handling with the destination owner before connecting automated updates.',
    jira: 'Use Jira when the receiving project is part of the team’s incident follow-up process. Agree on the project, issue type, and completion behavior so automated updates do not create unowned or incorrectly closed work.',
  }[id];
  GUIDES[`notifications/${id}`].sections.unshift(section('purpose', `When ${channel.name} is the right destination`, [text(purpose), text('Choose an owner for this connection and confirm who is expected to respond. Treat destination credentials as secrets, review the selected event states, and test only with an approved audience. Creating a channel is not proof that every downstream action succeeds.')]));
}

// Every published route must have authored content; missing pages fail validation.
export function getGuide(sectionInfo, page) {
  const guide = GUIDES[`${sectionInfo.id}/${page.id}`] || HANDBOOK[`${sectionInfo.id}/${page.id}`];
  if (!guide) throw new Error(`Missing customer guide: ${sectionInfo.id}/${page.id}`);
  const screenshot = PRODUCT_SCREENS[`${sectionInfo.id}/${page.id}`];
  // Insert after the introduction without mutating shared content on repeated visits.
  const result = screenshot ? { ...guide, sections: [guide.sections[0], screenshot, ...guide.sections.slice(1)] } : guide;
  return { ...result, time: readingTime(result) };
}
