// Customer explanations. Examples are illustrative, not observations from a live tenant.
const p = value => ({ type: 'text', value });
const n = (title, value) => ({ type: 'note', title, value });
const t = (headers, rows) => ({ type: 'table', headers, rows });
const s = (id, title, ...blocks) => ({ id, title, blocks });
const lesson = (type, chapters) => ({ type, sections: chapters.map(([title, ...paragraphs], i) => s(`chapter-${i + 1}`, title, ...paragraphs.map(p))) });

export const HANDBOOK = {
  'collect-data/opentelemetry': lesson('Connection guide', [
    ['Use application instrumentation for application questions', 'OpenTelemetry provides a common way for instrumented applications and collectors to export metrics, logs, and traces. Use it when you need request-level context or already have an OTLP-producing source.', 'It is not a promise that enabling one SDK exports every signal. A trace-only setup can correctly report requests while producing no logs or metrics. Decide which evidence is needed and configure the corresponding exporters or collector pipelines.'],
    ['Take the endpoint from your organization', 'Open Integrations → OpenTelemetry. Use the endpoint and language or collector example supplied by the current UI. The platform examples use OTLP over HTTP, with scoped API-key authorization. Keep keys out of source control and public browser code.', 'The generic exporter endpoint is a base URL; signal-specific endpoints include the final signal path. Check the SDK setting you are using so that /v1/traces, /v1/logs, or /v1/metrics is not appended twice. See the API reference for the current endpoint contract.'],
    ['Establish explicit service identity', 'Set an application service name that represents the software responsibility. Keep it consistent across instances and distinguish environments using supported resource context. Do not use a changing host or container name as a substitute for intentional application identity.', 'Instrumentation and propagation need to cover relevant boundaries for a distributed trace to be connected. Exporting spans from two services does not by itself guarantee that their requests share context.'],
    ['Verify a safe representative action', 'Perform an approved application action, then inspect the corresponding signal in ASTRA. Confirm the organization, service context, and event timestamp. Read exporter errors and OTLP rejection information if a request succeeds but the expected data is absent.', 'Check each enabled signal independently. Preserve exporter buffering according to your operational policy and use bounded retries for transient delivery problems rather than repeatedly sending an invalid payload.'],
  ]),
  'get-started/welcome': lesson('Overview', [
    ['What problem does ASTRA help you solve?', 'A system can look healthy at one layer while its users experience a failure at another. A cloud resource may be running, a host may be sending measurements, and an application request may still time out. ASTRA gives you places to inspect these different observations without treating them as interchangeable.', 'Use the platform to move from a question to evidence: identify the affected resource, choose a time window, and inspect the available metrics, logs, traces, or events. The value is context, not simply having more charts. A useful investigation can explain what changed, which system was involved, and which evidence supports the next action.'],
    ['Choose your first use case', 'For a machine-level question, start with host or cloud collection and the workload inventory. For a slow request, begin with application instrumentation and traces. For a recorded error message, start with Logs and confirm that the application’s log source is actually being collected.', 'Connect one authorized source first. Check its newest observation before adding more integrations. This makes it easier to distinguish an installation problem from a permissions problem or a filter hiding the data.'],
    ['Understand what a view can—and cannot—tell you', 'An empty trace view does not establish that an application has no requests: tracing may not be configured or a request may not have been sampled. A recently observed host does not establish application health. A suggested explanation is not the same as a proven cause.', 'Keep your organization and time range consistent when comparing views. Treat source, identity, units, and timestamps as part of the evidence rather than incidental details.'],
    ['Build a useful operating habit', 'After verifying a source, save a dashboard for a recurring question or create a monitor for a condition that needs a response. Agree who owns that response and how to verify recovery. Start with a small set of useful checks rather than trying to alert on every measurement.'],
  ]),
  'collect-data/aws': lesson('Connection guide', [
    ['Why connect an AWS account?', 'The AWS integration provides resource context and supported provider telemetry. This is useful when you need to understand what exists in an account or region and relate an operational symptom to a cloud resource. It is not a replacement for every form of host or application instrumentation.', 'For example, a cloud resource can be discovered even when guest memory measurements or application logs are unavailable. Plan the connection around the question you want to answer, then add an Agent or application exporter only where that evidence is needed.'],
    ['Prepare the account and collection scope', 'Confirm the customer organization, intended AWS account, and regions with your cloud administrator. Open Integrations and choose AWS. Use the current connection flow to obtain the required access instructions; do not reuse a trust policy or credential from a different organization.', 'Review requested permissions with the administrator. Resource discovery, metrics, logs, and cost data can have different prerequisites. A connection that can discover resources should not be assumed to have permission for every optional source.'],
    ['Verify discovery before interpreting coverage', 'After connecting, inspect the connection status and the discovered account and region context. Find an expected resource, then check whether recent metric or log observations are present. Verify the exact resource rather than using its display name alone.', 'If resources appear but a signal is empty, first confirm that collection for that signal is enabled and authorized. Check the selected region and time window before changing permissions.'],
    ['If the expected account is missing', 'Separate an authentication failure from an authorized connection with no matching resources. Check the account selection, integration error category, and requested scope. Ask an authorized administrator to correct access; never paste access keys, session tokens, or raw policies containing sensitive account context into public documentation.'],
  ]),
  'collect-data/azure': lesson('Connection guide', [
    ['Use Azure context to narrow an investigation', 'An Azure connection helps you find supported resources in subscriptions and relate telemetry to cloud context. It is useful when a team needs to distinguish which subscription or resource group contains the affected workload, rather than searching by a reused name.', 'Provider discovery does not automatically create application spans or collect every application file. Think of Azure inventory as one layer of evidence and application instrumentation as another.'],
    ['Agree on the subscription boundary', 'Open Integrations and select Microsoft Azure in the intended organization. Follow the current connection form with your Azure administrator. Confirm the tenant, subscription, and approved identity before submitting access details.', 'Give the integration the permissions required by the displayed workflow and your chosen collection scope. Keep credentials in the connection form or approved secret-management process, not in tickets or screenshots.'],
    ['Confirm the resource and signal separately', 'Locate a resource you expect to discover and check its subscription and resource-group context. Next examine the latest observation for the signal you want. An existing resource with no recent measurements calls for a collection check, not an immediate reconnection.', 'When comparing views, use the same organization, subscription, and time range. An account-level overview and a narrowly filtered workload can legitimately show different populations.'],
    ['Maintain the connection safely', 'If access stops working after a credential or role change, review the connection error with the identity owner. Rotate or repair through the supported integration flow. Avoid deleting and recreating connections as a first diagnostic step because it can obscure which scope or credential caused the problem.'],
  ]),
  'collect-data/gcp': lesson('Connection guide', [
    ['Why project context matters', 'Google Cloud projects are an important boundary for resource ownership and collection scope. Connecting the intended project lets your team investigate supported resources with that context instead of relying on names that may be repeated across environments.', 'Use cloud collection for provider evidence. If the question concerns an application transaction or a log file inside a machine, verify the corresponding application or host collection path as well.'],
    ['Prepare an approved connection', 'In the correct ASTRA organization, open Integrations and select Google Cloud. Work with the project administrator to follow the current access instructions. Confirm the intended project and the identity authorized to read its supported telemetry.', 'Do not upload a broad credential merely to get past an error. Match access to the required collection scope and keep credential material out of documentation, chat, and copied screenshots.'],
    ['Check an expected resource', 'After the connection is accepted, find a known resource and verify its project context. Inspect the newest measurement or record for that resource. This separates successful discovery from actual signal coverage.', 'If the view is empty, check project and time filters, collection status, and permissions in that order. Another project reporting successfully proves that some collection works; it does not prove access to this project.'],
    ['Interpret coverage honestly', 'A missing signal can mean unsupported collection, disabled configuration, missing permission, or no matching observations. Record which of these has been checked before escalating. Include a sanitized error category and time window, not a service-account key.'],
  ]),
  'collect-data/kubernetes': lesson('Connection guide', [
    ['Cluster discovery and workload telemetry are different', 'Kubernetes context helps explain where a workload runs: a cluster, namespace, and workload are more useful than a container name alone. Use this context when a replica changes, a workload moves, or several environments share similar names.', 'Connecting a cluster does not imply that every application exports traces. Infrastructure observations and application telemetry must be verified independently.'],
    ['Choose the connection path shown by ASTRA', 'Open Integrations → Kubernetes and follow the path supported for your environment. The current connection UI includes managed-cluster context and telemetry setup information. Confirm the cluster you intend to connect and the organization that should receive its data.', 'Have a cluster administrator review access and any collection configuration before applying it. Do not install a broad cluster credential or change workloads merely to illustrate a documentation example.'],
    ['Validate identity before counting workloads', 'Compare the cluster and namespace context of a known workload with the inventory. Then check recent observations on that workload. Several replicas can belong to the same application; a change in pod identity is not automatically a new business service.', 'Keep the incident time window in view. Short-lived workloads can have valid historical observations even when they are no longer running.'],
    ['Investigate gaps one layer at a time', 'If cluster context is absent, inspect connection and discovery status. If the workload exists but metrics are absent, inspect its collection path. If traces are absent, inspect application instrumentation and export. This sequence avoids treating every gap as a Kubernetes access problem.'],
  ]),
  'collect-data/rabbitmq': lesson('Connection guide', [
    ['What broker telemetry adds', 'RabbitMQ monitoring helps you distinguish a messaging backlog from an application error. A producer may successfully publish while consumers are unable to keep up. Broker evidence gives the team a way to examine queue and broker behavior alongside application observations.', 'Use the integration to investigate the broker itself. End-to-end message processing time requires suitable application instrumentation; a queue measurement alone does not describe the complete business transaction.'],
    ['Connect an approved broker', 'Open Integrations → RabbitMQ in the intended organization. Use the connection details and collection instructions presented by the current form. Ask the broker owner to approve the endpoint and monitoring credentials.', 'Limit access to what collection requires. Do not publish broker passwords, management endpoints, or sensitive queue names in shared examples.'],
    ['Read backlog in context', 'Start with the available queue, connection, and broker observations. Compare backlog over time with producer and consumer behavior rather than treating a single value as a verdict. A short burst that drains is different from sustained growth.', 'For an illustrative incident, a growing backlog and a drop in consumer activity suggest checking consumer availability. They do not by themselves establish why consumers stopped. Use application logs or traces to investigate the next boundary.'],
    ['Confirm recovery', 'Verify that new measurements arrive and that the observed queue behavior returns to an acceptable pattern. A successful connection test only proves the tested access path; it does not establish that messages are being processed within your business target.'],
  ]),
  'collect-data/collection-health': lesson('Troubleshooting', [
    ['Start with the failing boundary', 'Collection health answers whether data is moving through a source and its delivery path. It is different from application health. An application can be failing while its collector reports normally, or running normally while telemetry delivery is interrupted.', 'Identify whether you are missing an entire source, one signal, or only recent records. Write down the expected source and approximate time before changing settings.'],
    ['Use timestamps as evidence', 'Review source activity and the newest accepted observation where available. Compare those timestamps with the data view. If the source is current but the view is empty, check scope and filters. If both are stale, investigate source activity and delivery.', 'A recovered backlog may produce old event timestamps. Verify that genuinely new observations advance after recovery, rather than assuming any returned record proves the issue is fixed.'],
    ['Choose the next diagnostic action', 'Authentication errors call for key or permission review. Connection errors call for endpoint and network checks. A readable source producing no new records calls for application-side verification. Rejected records call for checking the supported payload or source contract.', 'Change one factor at a time and keep a sanitized record of what changed. Reinstalling or resetting state first can destroy useful evidence and create duplicates without resolving the original cause.'],
    ['Prepare an escalation that can be acted on', 'Share the affected signal, collector version, UTC interval, safe error category, and whether other sources still work. Do not share credentials or unreviewed log bodies. These details help distinguish a broad outage from one source’s configuration.'],
  ]),
  'infrastructure/overview': lesson('Overview', [
    ['A resource inventory is the beginning, not the conclusion', 'Infrastructure views help you understand what resources ASTRA has observed and which evidence is associated with them. Use them when a symptom is tied to a machine, cloud resource, network boundary, or database rather than a single request.', 'Discovery establishes resource context. Metrics, logs, and runtime events add observations about that resource. These layers can update at different times, so inventory presence should not be mistaken for complete telemetry coverage.'],
    ['Choose the view that fits the question', 'Workloads is the starting point for inspecting an observed entity and its signals. Service health helps narrow attention by resource state. Topology explains available relationships. Network, exposure, and change views answer narrower questions about connectivity and configuration.', 'For example, if a host becomes slow after a configuration change, begin with the host’s incident window, compare relevant measurements, and then inspect recorded changes. A topology edge can help identify where else to look, but it is not proof of causation.'],
    ['Keep comparisons meaningful', 'Use the same account, environment, and time window across views. Confirm the resource identity where possible and treat names as labels. Missing observations should be reported as missing—not as zero utilization or healthy status.', 'Once you find relevant evidence, follow the associated resource into a signal-specific investigation. Save a dashboard only after deciding which measurements answer the question repeatedly.'],
  ]),
  'infrastructure/service-health': lesson('Interpretation guide', [
    ['Resource state is not the same as user experience', 'Service health provides a way to review resource state across connected scopes. It helps you identify which resources deserve closer inspection before opening every workload individually.', 'A resource marked as running or recently observed may still host an application that fails requests. Conversely, a stale resource observation may reflect delayed collection rather than a stopped machine. Read the source and freshness alongside the state.'],
    ['Narrow the affected population', 'Start with the account or environment related to the reported problem. Inspect resources that are unhealthy or unexpectedly absent, then open the associated workload and compare recent telemetry.', 'Avoid comparing a production-only view with an all-environments view. The totals and apparent health distribution can differ simply because the selected resources differ.'],
    ['Turn a state into an investigation', 'If a resource is reported as unhealthy, identify the observation that supports the status and its timestamp. Compare the incident window with metrics, logs, and recorded changes. Document whether the evidence describes the resource itself or an application on it.', 'Use a recovery check that matches the symptom. A return to running state is helpful, but a request failure also needs request-level verification before the incident can be considered resolved.'],
  ]),
  'infrastructure/databases': lesson('Interpretation guide', [
    ['Separate availability, workload, and performance', 'Database monitoring is useful when application symptoms might be related to connection pressure, expensive work, or database resource constraints. Different database engines expose different evidence; the existence of an integration does not mean every engine-specific metric is available.', 'Begin by confirming the monitored engine and collection coverage. Missing query evidence is not proof that the database is idle.'],
    ['Read database evidence alongside application behavior', 'Inspect the database view for the affected time interval, then compare it with application request latency and errors. A shared rise can justify a deeper investigation but does not establish that the database caused the application symptom.', 'For example, connection pressure could be caused by increased demand, slow queries, or an application connection leak. Look for evidence that distinguishes those explanations rather than choosing one from a single graph.'],
    ['Review recommendations before changing the database', 'Treat recommendations as candidates for investigation. Confirm the engine, workload pattern, sample freshness, and operational constraints with the database owner. Review cost and availability implications before changing capacity or configuration.', 'After an approved change, compare equivalent workload periods and verify application behavior. Keep rollback planning with the owner; documentation should not encourage executing unreviewed database changes.'],
  ]),
  'infrastructure/topology': lesson('Concepts', [
    ['Why relationships matter', 'A list tells you which resources were observed; topology helps you understand how available evidence connects them. This is useful for choosing the next resource to inspect when an issue crosses infrastructure or service boundaries.', 'Treat the graph as a map of supported observations, not a complete diagram of everything that exists. Collection scope and instrumentation determine which nodes and relationships are available.'],
    ['Read a connection before following it', 'Start from a known affected entity. Inspect its context and the meaning of the visible relationship before moving to a neighbor. A hosting relationship, cloud association, and observed request dependency answer different questions.', 'Two connected nodes do not prove that a failure propagated between them. Use timestamps and underlying measurements or requests to test that hypothesis. A missing edge can also mean missing evidence rather than no relationship.'],
    ['Use topology to reduce the search space', 'Suppose an application request is slow and its service has a database dependency. The graph can point you toward the database, but request spans and database observations are needed to determine whether that dependency contributed to latency.', 'Keep the investigation scoped to the relevant environment and time range. Prefer following a small number of evidence-backed connections to expanding the entire graph and treating visual proximity as significance.'],
    ['When the graph looks incomplete', 'Check whether the relevant resources and telemetry sources are collected and correctly associated. Compare a known entity’s detail view with the graph. Report the missing relationship type and observation window when escalating; do not assume the UI should infer a dependency from similar names.'],
  ]),
  'infrastructure/network': lesson('Interpretation guide', [
    ['Network visibility depends on the evidence collected', 'Network views help explain traffic and connectivity in the scopes supported by your integrations. They can provide useful context for data transfer and communication patterns, but should not be interpreted as universal packet capture.', 'Before answering a connectivity question, check what network-log or cloud evidence is available for the account and interval. No traffic in a filtered view is not proof that no packets were exchanged.'],
    ['Investigate one connection question', 'Identify the source, destination, expected protocol, and symptom. Narrow the scope and time interval, then inspect available traffic or reachability evidence. Compare this with application timeout or error records.', 'An illustrative timeout can originate in name resolution, connection establishment, a policy boundary, or the application itself. Use the observed evidence to choose the next check rather than assuming every timeout is a network block.'],
    ['Understand cost and security context', 'Traffic volume can help identify transfer patterns worth reviewing, while reachability and exposure evidence help frame security questions. These are different interpretations of network context and should not be collapsed into a single health verdict.', 'Ask the responsible operator to validate policy or routing changes. After any approved change, recheck the original application symptom as well as the network observation.'],
  ]),
  'infrastructure/change-log': lesson('Investigation guide', [
    ['Use changes to form a hypothesis', 'The infrastructure change log helps you inspect recorded resource configuration changes. It is useful when an operational symptom appeared around a deployment or settings change and you need to narrow possible explanations.', 'A change before a failure is a candidate explanation, not proof. The change view may not contain every action performed outside collected systems.'],
    ['Compare the correct interval', 'Locate the affected resource and inspect changes before and during the symptom window. Compare the change timestamp with measurements and logs. Allow for collection delay and timezone differences when aligning events.', 'Record what changed, which resource it applies to, and what evidence would support or contradict its relevance. Avoid concluding that the most recent change must be responsible simply because it is visible.'],
    ['Verify rather than immediately reverse', 'Review the proposed explanation with the resource owner. If a rollback is considered, evaluate dependencies and the risk of losing intentional changes. The documentation view itself does not authorize operational changes.', 'After an approved action, verify the original symptom and the resource state. Preserve the chronology so a later review can distinguish the initial change, the observed impact, and recovery.'],
  ]),
  'infrastructure/exposure': lesson('Interpretation guide', [
    ['Exposure is a review signal', 'Internet exposure views help you review evidence that a workload or resource may be publicly reachable. This matters when a resource is intended to be private or when a public service needs a clear owner and access policy.', 'Public exposure is not automatically a vulnerability, and absence from the view is not a security certification. Interpret each entry according to the source, collection coverage, and intended design.'],
    ['Review intent and observed configuration', 'Identify the resource and determine whether public access is expected. Check the available evidence and its freshness with the owner. Compare the observed state with the intended entry points and any documented restrictions.', 'For an intentionally public application, the next question may concern authentication and permitted traffic. For an internal database, an unexpected public entry should be escalated for review rather than ignored because the database currently appears healthy.'],
    ['Make a safe follow-up decision', 'Do not perform intrusive scans or close access paths solely from a documentation example. Use the approved security process and have the resource owner validate any change.', 'After remediation, verify the relevant configuration and collection freshness. Record evidence of the changed state without including sensitive addresses or access credentials in public reports.'],
  ]),
  'applications/overview': lesson('Overview', [
    ['Start with the experience that is failing', 'Application views help you investigate requests, services, errors, and supported user sessions. They are most useful when you can describe the affected action: checkout is slow, a job fails, or a page does not load.', 'Infrastructure measurements explain resource behavior; application telemetry explains work performed by software. You often need both, but a healthy host alone cannot demonstrate that an application action succeeds.'],
    ['Choose the right evidence', 'Services establish application context. Requests and traces show instrumented execution. Errors help group failure evidence. Sessions provide browser-side context when real-user monitoring is configured.', 'If an application view is empty, confirm the relevant instrumentation and export path. Installing a host collector does not by itself establish complete application tracing or real-user monitoring.'],
    ['Follow one incident through the views', 'Choose the affected service and time window, inspect a representative failing or slow request, and follow the relevant dependency. Compare errors or session evidence where available.', 'Keep conclusions proportional to coverage. A sampled request is one observation, not a complete count of all user actions. Confirm a repeated pattern before generalizing to the whole application.'],
  ]),
  'applications/services': lesson('Concepts', [
    ['A service gives requests a stable application context', 'A service represents application identity in the telemetry ASTRA receives. Use it to organize requests and related evidence around a software responsibility rather than around whichever host currently runs it.', 'Service, instance, and version describe different things. A service can run on several instances, and a release can introduce a new version without becoming a different service. Consistent instrumentation names make comparisons more useful.'],
    ['Read identity before reading performance', 'Inspect the service name, available version and instance context, and recent activity. Confirm that you are looking at the intended environment. Similar names in different scopes should not be assumed to describe the same workload.', 'Do not manufacture a service name from a host or container identifier merely to populate this view. Infrastructure-only telemetry can be valid without a service association.'],
    ['Use a service as the investigation entry point', 'When a symptom affects one application, compare its requests and errors in the incident window. Follow available dependencies to narrow the next question. If only one instance is affected, investigate that instance before applying a service-wide conclusion.', 'After a release, compare equivalent periods and workload patterns. A changed traffic mix can alter latency even when the software is unchanged.'],
  ]),
  'applications/requests': lesson('Investigation guide', [
    ['Use requests to examine a unit of work', 'A request is a useful boundary for understanding what the application was trying to accomplish. Depending on instrumentation, that work can be a web request or a background operation. Its recorded execution can reveal where time was spent and where errors were observed.', 'Start with an operation and symptom rather than opening the slowest record without context. High duration may be expected for one operation and unacceptable for another.'],
    ['Compare like with like', 'Choose the affected service, operation, and incident window. Compare failed or slow executions with successful examples of the same operation. Examine which hops or dependencies differ.', 'An upstream timeout can be recorded separately from a downstream failure. Follow the chronology and span relationships instead of counting every error as an independent incident.'],
    ['Recognize incomplete evidence', 'Sampling, missing propagation, or partial instrumentation can leave gaps. A missing child span does not prove that no downstream work occurred. Use available logs and resource observations to test the explanation.', 'Keep the distinction between observed duration and inferred cause explicit in the investigation. The objective is a supported next action, not simply identifying the longest bar.'],
  ]),
  'applications/errors': lesson('Investigation guide', [
    ['An error is evidence, not a diagnosis', 'Error views help you find recurring failure patterns from available application telemetry. They are useful for separating one isolated event from a pattern tied to an operation, service, or release.', 'A message may describe the point where failure was detected rather than where it began. A connection error in a client can have several underlying explanations.'],
    ['Establish scope and recurrence', 'Inspect the affected service and time interval. Compare the error pattern with traffic and recent changes. A higher count during higher traffic is different from a higher failure proportion under similar demand.', 'Review a representative record and its context. Where related requests or logs are available, use them to understand the work being performed when the error occurred. Avoid copying sensitive stack details or log bodies into public reports.'],
    ['Verify the proposed fix', 'State which evidence supports the explanation and what would demonstrate recovery. Check whether the pattern stops under comparable traffic and whether the affected operation succeeds.', 'A quiet error view can also reflect missing telemetry. Confirm collection freshness before treating absence of errors as proof of recovery.'],
  ]),
  'applications/sessions': lesson('Interpretation guide', [
    ['See an issue from the browser side', 'Supported real-user session evidence helps relate user actions, page behavior, and recorded errors. It can explain a symptom that backend metrics alone do not show, such as a slow page experience with otherwise normal server measurements.', 'This evidence requires the appropriate browser instrumentation. A server Agent or cloud integration does not automatically create user-session data.'],
    ['Follow the affected action', 'Use the session and time context available in the product to inspect the action associated with the report. Compare page behavior and errors, then follow related request evidence where it exists.', 'Do not assume a session is a screen recording. Interpret only the events and measurements actually provided by the configured instrumentation.'],
    ['Protect the people behind the data', 'Session information can contain personal or application-specific context. Limit access to authorized users and follow your organization’s collection and retention policies. Share sanitized descriptions rather than unrestricted session details.', 'Confirm whether an issue affects one browser context or a broader group before generalizing. Missing sessions can reflect instrumentation, consent, or delivery conditions and should not be interpreted as no users.'],
  ]),
  'telemetry/traces': lesson('Concepts', [
    ['A trace follows instrumented work', 'A trace groups spans that describe pieces of a request or operation. Each span contributes timing and context. This is useful when a slow user action crosses several services and a host-level chart cannot explain which part took time.', 'Traces depend on instrumentation and context propagation. They are not automatically available simply because metrics or logs are arriving.'],
    ['Read the span tree as evidence', 'Start with the root operation and inspect its duration and status. Follow relevant child spans and compare their timing. Parallel child spans overlap, so adding all their durations is not a reliable way to calculate total request time.', 'For an illustrative request, a long database span is a reason to inspect database behavior. It is not proof that adding database capacity will resolve the problem. Query shape, contention, and workload can require different responses.'],
    ['Understand why a trace may be incomplete', 'Sampling can exclude requests. Missing propagation can split related work into different traces. Uninstrumented components can appear as unexplained time. Check these boundaries before interpreting a gap as no activity.', 'Use span attributes and associated service context carefully; avoid relying only on display names. Follow related logs when correlation is available and keep the same time interval.'],
    ['Confirm an improvement', 'Compare the same operation under similar conditions before and after an approved change. Look at a pattern of requests rather than one unusually fast trace. Verify that collection and sampling did not change in a way that explains the apparent improvement.'],
  ]),
  'telemetry/events': lesson('Interpretation guide', [
    ['Events describe observations at a point in time', 'Runtime and operational events help answer what changed: a process was observed, a container stopped, or a health check changed state. They complement metrics, which describe measurements over time, and logs, which can carry arbitrary application records.', 'An event is only as authoritative as its source. Read the exact kind, timestamp, provenance, and associated resource before assigning meaning.'],
    ['Distinguish a baseline from a transition', 'A sample event describes an observed state. It is not automatically evidence that something just started. A lifecycle transition describes a change supported by the collector’s observations.', 'For example, discovering an already-running container should not be interpreted as the moment it started. This distinction matters when building an incident timeline or comparing events with a deployment.'],
    ['Correlate without inventing identity', 'Use the associated entity and exact resource identifiers where provided. A container name or hostname can be reused; an event body alone is not a reliable identity key. Host-level events may legitimately have no application service association.', 'Compare event time with the incident interval. Retried delivery can bring older evidence into the platform later, so arrival time and event time should not be treated as interchangeable.'],
    ['Use a timeline to test explanations', 'Build a sequence of relevant observations and compare it with symptoms. A restart followed by a recovery may support a hypothesis, but does not prove the restart addressed the underlying cause. Record gaps and uncertainty rather than filling them with assumed transitions.'],
  ]),
  'monitoring/triage': lesson('Investigation guide', [
    ['Triage is about deciding what needs attention first', 'Triage narrows a stream of observations into an actionable problem. Start with user impact, affected scope, and current evidence rather than treating every warning as an equally urgent incident.', 'Several signals can describe the same underlying problem. A host issue, request failure, and notification may be related rather than three independent incidents.'],
    ['Establish the current situation', 'Choose the relevant scope and incident window. Identify affected entities, inspect the latest evidence, and distinguish ongoing impact from a recovered historical event. Compare with recent changes where available.', 'Write a short statement of the symptom and what is known. For example: requests to one operation are failing during this interval while other operations continue. This is more useful than a broad assertion that the platform is down.'],
    ['Choose an owner and next check', 'Route the investigation to a team that owns the affected system. Include the entity, interval, and evidence that supports the escalation. Keep speculative causes labeled as hypotheses.', 'Before closing the loop, verify the original symptom and collection freshness. A cleared alert alone may not establish that all user impact ended.'],
  ]),
  'monitoring/monitors': lesson('Concepts', [
    ['A useful monitor represents a decision', 'A monitor evaluates a condition your team cares about. Its purpose is not to alert on every movement in a chart, but to detect a situation that deserves a defined response.', 'Choose a signal with adequate coverage and an owner who can act. A threshold without an investigation path often creates noise instead of useful detection.'],
    ['Scope, time, and recovery belong together', 'Use the monitor editor to choose the supported signal, scope, and evaluation settings. Consider how long a condition should persist and how recovery should be recognized using the options the editor exposes.', 'A brief resource spike and sustained saturation can have different operational meanings. Also decide how missing data should be investigated; absent measurements are not equivalent to a measured zero.'],
    ['Review existing checks before adding another', 'Inspect monitors that already cover the same entity or symptom. Similar checks can create duplicate notifications and make ownership unclear. Give each check a descriptive name that states the condition and intended scope.', 'After saving, review evaluations and notification delivery under approved test conditions. A saved configuration is not proof that the monitor will detect the intended failure.'],
    ['Tune with evidence', 'When a monitor is noisy, investigate whether the scope, condition, or response expectation is wrong before simply raising a threshold. Compare notifications with actual incidents and document why a change improves the signal.'],
  ]),
  'monitoring/first-monitor': lesson('Tutorial', [
    ['Define the response before the threshold', 'Pick one observable condition that matters to your team and name its owner. An example is a sustained resource constraint on an important host. Decide what the responder should inspect when the condition occurs.', 'Verify that the required telemetry is recent and consistently collected. A monitor cannot compensate for a missing source, and a healthy-looking chart outside the target scope does not establish coverage.'],
    ['Create a focused check', 'Open Monitors and use the available creation flow. Choose the intended entity or scope, select a supported signal, and configure the condition and evaluation options shown by the editor. Use a name that makes the affected system and condition recognizable.', 'Base the settings on a meaningful baseline and operational tolerance. Do not copy a numeric threshold from an unrelated environment merely because it is common.'],
    ['Connect the notification path', 'Configure an approved notification channel and choose relevant event states. Verify its destination with a safe test. Channel delivery and monitor evaluation are separate checks: a successful email test does not validate the monitor condition.', 'Avoid deliberately disrupting a production service to demonstrate an alert. Use an approved test scope or review observed evaluations with the system owner.'],
    ['Know when the setup is complete', 'Confirm that the saved monitor targets the intended scope, receives its required evidence, and has a clear response owner. Verify notification receipt and recovery handling where a safe test is available.', 'Record what the responder should check first and how to decide that impact has ended. This makes the monitor useful beyond the person who created it.'],
  ]),
  'monitoring/incidents': lesson('Investigation guide', [
    ['An incident organizes a response', 'An incident provides a place to consider affected entities, evidence, chronology, and next steps together. Use it to coordinate understanding of a problem rather than treating each alert as a complete explanation.', 'Severity communicates urgency, but the evidence still needs interpretation. Separate confirmed impact from a suspected cause.'],
    ['Build the chronology', 'Read the available timeline and identify when symptoms began, which observations followed, and which actions were taken. Compare event timestamps rather than assuming the order of arrival is the order of occurrence.', 'Open associated resources or telemetry to validate important claims. Multiple related signals can support a hypothesis, but an AI-generated summary or topology link should not replace the underlying evidence.'],
    ['Review proposed actions with the owner', 'Check the target, scope, expected effect, and risk of any proposed action. Use the applicable approval flow; reading a recommendation is not authorization to execute it.', 'Keep notes clear about what was actually done. A proposed change, an approved change, and a completed change are different states.'],
    ['Close with a recovery statement', 'Verify the original symptom, the affected service or resource, and the freshness of observations. Preserve the explanation and remaining uncertainty so a recurrence can be investigated faster.', 'If symptoms stopped without a confirmed cause, say so. A precise statement of uncertainty is more useful than an unsupported definitive diagnosis.'],
  ]),
  'monitoring/synthetics': lesson('Connection guide', [
    ['Test availability independently of user traffic', 'Synthetic monitoring runs supported HTTP, TCP, or DNS probes. It is useful when you want evidence about a target even when no real user request is currently being observed.', 'A successful probe establishes only what that probe tested. A TCP connection does not demonstrate a successful login, and a DNS response does not prove an application is healthy.'],
    ['Choose the protocol for the question', 'Use HTTP for supported endpoint response checks, TCP for connection establishment, and DNS for name resolution. Select a target that you are authorized to probe and review the settings exposed by the current creation flow.', 'Do not put secrets in a publicly shared target URL. Avoid aggressive probing or sensitive endpoints without approval from their owner.'],
    ['Interpret failures in sequence', 'Examine repeated results and their timing rather than treating one failure as a complete outage. Consider whether the observation reflects name resolution, connection, response behavior, or the vantage point of the probe.', 'Compare probe failures with application and infrastructure evidence in the same interval. A probe can detect a symptom before enough real-user traffic exists to make it visible elsewhere.'],
    ['Verify the monitoring intent', 'Confirm the target, schedule, and expected response are appropriate for the service. Decide who responds and how they verify recovery. When a synthetic check is green, describe the tested behavior rather than claiming the entire application is healthy.'],
  ]),
  'dashboards-reports/dashboards': lesson('Tutorial', [
    ['Design a dashboard around a recurring question', 'A dashboard is a saved operational view, not a requirement to display every available metric. Start with a question such as whether one service is under resource pressure or whether a recurring job is behaving normally.', 'Choose a small set of measurements that together answer that question. A beautiful chart with an unclear unit or scope is less useful than a simple chart that a responder can interpret.'],
    ['Make every panel interpretable', 'Use the dashboard creation and editing controls to select available signals and visualization options. Give panels meaningful titles and check their units, aggregation, and entity scope.', 'For example, a memory panel should make clear whether it shows usage, a limit, or a percentage. Do not compare series that use different units or represent different populations without explaining that difference.'],
    ['Test the view under another time range', 'Change the time window and confirm that the panels still answer the intended question. Inspect empty or sparse results and distinguish missing data from a measured zero.', 'Review the dashboard with someone who did not build it. They should be able to identify the subject, time range, and meaning of each panel without asking which hidden filter was applied.'],
    ['Keep interpretation close to the view', 'Use supported descriptions or your team’s accompanying documentation to explain what an abnormal pattern means and which investigation should follow. A dashboard should guide attention, not automatically prescribe an operational change.'],
  ]),
  'dashboards-reports/manage-dashboards': lesson('Administration guide', [
    ['Treat shared dashboards as maintained tools', 'Saved dashboards become part of a team’s operating routine. Their names, scope, and ownership matter because responders may depend on them during an incident.', 'Keep a clear distinction between personal exploration and a view other people rely on. Confirm the available sharing and editing permissions before making a dashboard part of an operational process.'],
    ['Review before modifying a shared view', 'Inspect the current panels, filters, and purpose. If a change alters the meaning of a familiar chart, notify its users and explain the difference. Renaming a panel does not correct an inconsistent aggregation or scope.', 'Remove redundant views only through an authorized process. Do not delete a dashboard solely because it currently shows no data; the selected time range or collector coverage may explain the empty result.'],
    ['Keep a useful catalogue', 'Use names that identify the service, team, or operational question. Periodically verify that each maintained view still points to the intended data and that its owner can explain its purpose.', 'After changes, open the dashboard with representative permissions and time ranges. Confirm that the saved view remains useful to the people expected to use it.'],
  ]),
  'dashboards-reports/reports': lesson('Interpretation guide', [
    ['Reports summarize a bounded view of evidence', 'Reports help communicate operational or business information from authorized platform data. They are useful when a team needs a repeatable review rather than an interactive investigation of one record.', 'A report’s meaning depends on its period, scope, and source coverage. A total is not useful unless readers understand what it includes and what is missing.'],
    ['Check the reporting boundary', 'Open the relevant report and review the organization, selected scope, and reporting interval. Check the freshness of its underlying data before comparing it with another period.', 'Separate a change in the measured system from a change in coverage. Adding a new account or source can increase a reported total even when existing resources behave the same way.'],
    ['Use reports to start a conversation', 'Investigate significant differences using the underlying resource or telemetry views. Explain exclusions and uncertainty when sharing a result, especially when cost or utilization is used to support a decision.', 'Before distributing a report, confirm that recipients are authorized to see its contents. Do not assume that access to a summary permits unrestricted sharing of its underlying customer data.'],
  ]),
  'notifications/notification-overview': lesson('Overview', [
    ['A notification connects detection to a responder', 'A monitor can identify a condition, but someone still needs to receive, understand, and act on it. Notification channels connect supported ASTRA updates to an approved communication or ticketing destination.', 'Choose the destination based on the response process. Chat can support collaboration, email can reach a distribution group, and ITSM tools can support ticket ownership. More destinations do not necessarily mean a better response.'],
    ['Choose the appropriate destination', 'The catalogue includes Email, Slack, Microsoft Teams, Webhook, ServiceNow, and Jira. Each has its own credentials, destination settings, and provider requirements. Review the corresponding guide rather than assuming that every channel is configured like SMTP.', 'The channel forms expose Critical, Warning, and Recovered selections for monitor state changes. Other supported workflows may have their own behavior; event checkboxes should not be assumed to define every possible platform notification.'],
    ['Verify receipt, not just a successful request', 'Use the saved channel’s Test action only with an approved destination. Review Last test and Deliveries, then confirm the message or ticket at the receiving system.', 'An accepted webhook or SMTP request can still be followed by downstream processing or filtering. The platform’s recorded send attempt and the recipient’s experience are different pieces of evidence.'],
    ['Keep the route maintainable', 'Use a recognizable display name, a maintained destination, and credentials owned by the appropriate team. Review channels after team or provider changes. Disable an unused route rather than allowing notifications to go to an abandoned mailbox or workflow.'],
  ]),
  'costs/unit-economics': lesson('Concepts', [
    ['From infrastructure spend to a business question', 'Unit economics relates infrastructure cost to dimensions such as a team, product, or customer. It is useful when a raw cloud total does not explain who is responsible for spend or which activity creates value.', 'The relationship depends on attribution and the available cost data. A precise-looking number can still be incomplete if resources are unassigned or the selected billing period is not complete.'],
    ['Read the scope before comparing costs', 'Inspect the period, currency or units shown, business dimension, and allocation coverage. Compare like-for-like scopes. A change in allocation rules can move spend between teams without changing the total infrastructure bill.', 'For an illustrative product review, distinguish total spend from cost per business unit. The latter needs a meaningful denominator; do not infer customer counts or transaction volumes that were not supplied.'],
    ['Use the result responsibly', 'Use cost context to identify questions for resource owners. Compare utilization and service requirements before interpreting spend as waste. A resource with low average utilization may provide resilience or handle periodic work.', 'Document assumptions and unallocated amounts in discussions. The objective is a defensible decision about resources, not a ranking based on incomplete attribution.'],
  ]),
  'costs/cost-attribution': lesson('Administration guide', [
    ['Attribution defines the meaning of a cost view', 'Cost attribution associates infrastructure spend with the dimensions used by your business. It lets a team discuss ownership and resource choices without relying only on account-level totals.', 'Before configuring rules, agree which dimension represents the decision: team, product, customer, or another supported business grouping. Different dimensions can answer different questions.'],
    ['Review coverage and ambiguity', 'Use the available attribution management controls to define and review the mapping. Examine resources that are unassigned or match ambiguous ownership. Do not silently treat an unallocated amount as zero cost.', 'For shared infrastructure, document the allocation assumption with the relevant owners. A mapping is a business interpretation; it does not prove that one team exclusively caused the spend.'],
    ['Validate the result after a change', 'Compare the overall scope and allocated amounts before and after editing. Check that expected resources moved into the intended dimension and that the change did not simply hide unmatched data.', 'When presenting trends, note changes in attribution policy. Otherwise readers may interpret a bookkeeping shift as a real efficiency improvement or regression.'],
  ]),
  'costs/optimization': lesson('Decision guide', [
    ['An opportunity is a candidate for review', 'Optimization views help identify resources or patterns worth examining with cost and utilization context. They are a starting point for a resource owner’s decision, not permission to resize or remove infrastructure automatically.', 'Low average utilization may reflect burst demand, scheduled work, or redundancy requirements. Consider the observation period and service constraints before labeling a resource wasteful.'],
    ['Check the operational trade-off', 'Inspect the affected resource, the available utilization evidence, and the cost scope. Ask whether the proposed change preserves availability, performance, and recovery requirements.', 'For example, reducing capacity may lower recurring cost but also remove headroom needed for a periodic job. A useful recommendation should be tested against that workload rather than evaluated only against an average.'],
    ['Verify savings and service behavior', 'After an approved change, compare equivalent periods and confirm the intended resource state. Review both cost and operational evidence; an apparent saving is not successful if it creates unacceptable impact.', 'Record the assumptions and follow-up checks. Avoid presenting an estimated opportunity as realized savings until the appropriate cost period and evidence are available.'],
  ]),
  'astra-intelligence/astra-agents': lesson('Concepts', [
    ['Specialized assistance is different from collection', 'ASTRA agents in the application are investigation assistants; the Linux Host Agent is a collector installed on a machine. Distinguishing these roles avoids expecting an investigation assistant to supply telemetry that has never been collected.', 'Use assistant activity to understand how an investigation is being approached and which evidence supports its conclusions.'],
    ['Review the evidence behind collaboration', 'Inspect the available tasks, findings, and supporting context. Separate an observed fact from an inference or proposed next step. If an assistant has incomplete source coverage, its explanation may be incomplete as well.', 'For an illustrative incident, one assistant might focus on resource behavior and another on application evidence. Agreement between summaries is not a substitute for checking the underlying observations.'],
    ['Retain human control of operational decisions', 'Review recommendations with the responsible owner and use the required approval flow for any action. Do not treat a generated suggestion as an instruction to execute commands or broaden access.', 'Keep secrets and unnecessary customer information out of prompts. Share only the context needed for the authorized investigation and verify recovery independently after an approved action.'],
  ]),
  'astra-intelligence/analyzer': lesson('Interpretation guide', [
    ['Bring several perspectives to one workload', 'Analyzer brings available health, cost, security, and operational context into a workload review. This is useful when a decision spans more than one dashboard or a single metric would miss an important trade-off.', 'Coverage depends on connected sources. A missing finding may mean missing evidence, not an absence of risk.'],
    ['Start with a concrete question', 'Choose the relevant workload and review its context. Inspect findings that relate to the question you are trying to answer, then open supporting observations where available.', 'If a workload is expensive and slow, investigate both symptoms rather than assuming one proposed change improves both. Capacity reduction may conflict with performance requirements.'],
    ['Separate findings from decisions', 'Treat a finding as a prompt to review the evidence, assumptions, and intended scope. Confirm identity and freshness before making a recommendation to the system owner.', 'Document which conclusions were verified and which remain hypotheses. Operational changes still require the appropriate permissions and approval outside the act of reading an analysis.'],
  ]),
  'astra-intelligence/code': lesson('Decision guide', [
    ['Connect a failure to relevant code context', 'ASTRA Code supports investigating application errors with available code context and reviewing proposed changes. It is useful when operational evidence points toward software behavior rather than only infrastructure state.', 'A proposed patch is not proof that the cause has been fixed. Source access, the relevant version, and a reproducible symptom all affect how reliable the suggestion can be.'],
    ['Check the version and evidence', 'Confirm the repository and version associated with the affected application. Read the error context and the proposed explanation together. A correct change for one version may be irrelevant to a different deployed version.', 'Avoid including secrets or unnecessary customer payloads in a code investigation. Use the approved repository integration and permissions.'],
    ['Review as you would any code change', 'Inspect the scope, behavior, security implications, and tests. Verify that the proposal addresses the reported symptom without introducing unrelated changes. Follow your team’s review and release process rather than assuming an analysis result authorizes deployment.', 'After a separately approved release, compare the original failure pattern and confirm telemetry remains healthy. A quiet error view alone is not enough if collection stopped.'],
  ]),
  'astra-intelligence/ask-astra': lesson('Tutorial', [
    ['Ask a question that can be checked', 'Ask ASTRA is useful for exploring authorized operational context in natural language. Good questions include a subject, time window, and desired comparison. Vague requests such as “fix everything” do not define an evidence boundary.', 'For example: “What changed for this workload during the incident window?” is easier to verify than “Why is production bad?” The answer still depends on available telemetry and permissions.'],
    ['Provide scope without providing secrets', 'Name the relevant resource or service context and time interval using the information the application already exposes. Do not paste API keys, passwords, or unreviewed log bodies into the conversation.', 'If a question concerns missing data, say which signals are present and which are absent. This helps avoid an explanation based on evidence that was never collected.'],
    ['Read the answer critically', 'Check referenced observations and distinguish reported facts from suggested explanations. Ask a narrower follow-up if the answer does not establish the requested scope or time period.', 'Use the answer to guide investigation, not to bypass change approval. Verify the actual result of an action through the relevant telemetry and operational owner.'],
  ]),
  'administration/members': lesson('Administration guide', [
    ['Membership establishes access to an organization', 'A user identity and an organization membership are different. A person may have access to more than one organization, with different roles in each. Manage members in the organization whose access you intend to change.', 'This matters when onboarding a teammate or removing access after a responsibility changes. Editing one organization should not be treated as a global user-management action.'],
    ['Grant access for a responsibility', 'Use the available invitation and membership controls to add an authorized teammate. Assign a role that matches the work they need to perform, such as viewing evidence or managing an integration.', 'Do not give an administrative role solely to reveal a missing page. First identify the required permission and check whether a more limited role is appropriate.'],
    ['Verify changes from the member’s perspective', 'Confirm that the user selects the intended organization and receives the expected actions. A hidden integration can reflect permissions rather than missing platform support.', 'When access must end, use the supported membership and session controls according to your policy. Preserve required audit history and do not delete unrelated organizations or data as a shortcut.'],
  ]),
  'administration/roles': lesson('Concepts', [
    ['Roles group permissions around responsibilities', 'Roles let an organization manage access consistently instead of making every user an administrator. A permission typically distinguishes an action such as reading a view from managing its configuration.', 'The distinction is important for integrations: a user may be allowed to inspect existing connections without being allowed to create or edit them.'],
    ['Begin with the task, then choose access', 'List the work the user needs to perform and inspect the intended role’s permissions. Use the least privilege that allows that work. Review the effect of a role change on all members who use the role.', 'A catalogue entry missing for one member but visible to another is a reason to inspect permissions. It is not automatically a seed or installation failure.'],
    ['Validate tenant boundaries', 'Make changes in the correct organization and verify them with the affected membership. Platform administration and customer-organization access are separate concerns; one should not be assumed to grant the other.', 'Record the reason for administrative access and review it when responsibilities change. Avoid sharing one privileged login among several people because it undermines accountability.'],
  ]),
  'administration/projects': lesson('Concepts', [
    ['Projects organize context inside an organization', 'Projects help teams group supported resources and telemetry within the organization boundary. Environments add another useful distinction, such as production and staging.', 'These dimensions make views easier to interpret, but a label alone should not be assumed to create a separate security boundary. Use the actual permissions and scoping behavior provided by the platform.'],
    ['Choose names that support investigation', 'Use consistent project and environment names that reflect how teams own and operate systems. Review assignments when a resource or service changes responsibility.', 'For example, separating production and staging can prevent a healthy staging workload from obscuring a production incident. Unassigned resources should be reviewed rather than silently omitted from ownership discussions.'],
    ['Verify the effect on views', 'After an authorized assignment change, check the affected resource with and without the project filter. Ensure the change improves discoverability and does not make expected data appear missing.', 'When comparing reports or dashboards, keep the same project and environment selections. A scope difference can explain a changed total without any change in the system itself.'],
  ]),
  'administration/plan': lesson('Reference', [
    ['A plan window is part of access context', 'The organization plan has an availability window and status. Use the customer plan view to understand the organization’s current plan information, rather than relying on an old onboarding message.', 'Plan dates and organization access status are related but distinct. An account can exist while access through an inactive organization is unavailable.'],
    ['Read exact dates, not only a day count', 'Review the start and expiry timestamps and the displayed timezone. A remaining-duration label is a convenience; the exact timestamp determines the boundary.', 'When raising an access question, include the organization context and relevant displayed time without exposing credentials. Do not assume a browser refresh or session restart can extend an expired plan.'],
    ['Request a change through the appropriate owner', 'Plan changes are handled through the authorized administration process. Customer documentation should not direct ordinary members into platform-admin controls.', 'If access is unexpectedly denied, distinguish plan or organization status from a password problem. Ask the organization administrator to confirm the active membership and plan state.'],
  ]),
  'administration/audit': lesson('Interpretation guide', [
    ['Audit activity explains administrative actions', 'Organization audit activity provides a record of supported administrative actions. It helps answer who performed an action, what was affected, when it occurred, and the recorded result.', 'Audit events are not application logs and do not describe every operation in an external system. Interpret their scope according to the action and target recorded.'],
    ['Read a record in context', 'Select the relevant interval and inspect the actor, action, target, and outcome. Human-readable labels help scanning, while exact identifiers can help distinguish similarly named objects during authorized troubleshooting.', 'A failed or denied action is different from a successful change. Do not summarize an attempted action as completed without checking its result.'],
    ['Preserve the evidence', 'Use audit data to investigate access or configuration questions without rewriting the record. Share only the details needed by authorized reviewers and follow the organization’s retention and handling rules.', 'Correlate audit timestamps with operational evidence when investigating a change, but do not assume that temporal proximity proves causation.'],
  ]),
  'administration/sessions': lesson('Administration guide', [
    ['A session represents ongoing authenticated access', 'Session management is useful when access should end without deleting a person’s identity or historical activity. A successful login event describes the past; an active session describes current validity.', 'Do not infer that a session is still active simply because a user logged in successfully earlier. Expiry, logout, and revocation can end it.'],
    ['Review before revoking', 'Use the supported session controls within your authorized organization scope. Confirm the affected user and session context so you do not interrupt unrelated work.', 'Revoking a session can require the user to authenticate again. It should be part of a clear access or incident-response decision rather than a routine way to refresh a page.'],
    ['Verify the access outcome', 'After an authorized revocation, confirm that the targeted access is no longer valid. Other authorized organization users should remain unaffected.', 'If the user can sign in again, inspect whether their membership and credentials still authorize a new session. Ending one session is not the same as removing all future access.'],
  ]),
  'troubleshooting/authentication': lesson('Troubleshooting', [
    ['Distinguish sign-in from organization access', 'Authentication establishes identity; organization membership and status determine whether that identity can access the customer workspace. A correct password does not guarantee an active organization membership.', 'Start with the exact user-facing error and the intended organization. Avoid repeated password resets when the error concerns access rather than credentials.'],
    ['When there is no active organization membership', 'Ask the organization administrator to verify membership, organization status, and applicable plan state. A suspended or expired organization can prevent access even when the user identity still exists.', 'Do not attempt to work around the boundary with another tenant’s key or a shared administrator login. Access should be repaired through the supported administrative process.'],
    ['When a page or action is missing', 'If sign-in works but an integration or control is unavailable, review the current organization and role permissions. Reading and managing a feature can require different permissions.', 'After an authorized role change, renew the session as appropriate and verify the intended action. Do not grant broad administrative access without checking the specific need.'],
    ['Share a safe problem report', 'Include the user-facing error category, approximate time, intended organization, and whether other users are affected. Never include passwords, session tokens, or API keys.'],
  ]),
  'troubleshooting/agent-service': lesson('Troubleshooting', [
    ['A running service is only one checkpoint', 'The Linux Host Agent can be running while a source is unreadable or delivery is failing. Check configuration, source activity, export health, and the platform observation separately.', 'Avoid reinstalling first. It can obscure the original cause and may complicate retained state without repairing endpoint access or permissions.'],
    ['Check the local service with an authorized operator', 'Ask the host operator to inspect service status and recent service logs. Confirm the installed version and the intended configuration file. Review safe error categories without copying secrets or the full configuration into a support message.', 'If startup fails, validate the configuration through the supported Agent validation command or installer flow. Do not weaken the service sandbox to suppress an error.'],
    ['Separate one failed capability from a broad outage', 'If host metrics arrive but file or journal logs do not, inspect the specific source and service-account access. If Docker is unavailable, check whether Docker collection is enabled and operator-approved socket access exists.', 'A capability-specific permission issue does not justify broad filesystem or Docker socket permission changes. Escalate the exact access requirement to the host owner.'],
    ['Preserve delivery state', 'If delivery is delayed, review endpoint reachability, authentication, and queue health with the operator. Retained data can replay after recovery. Do not delete queues or checkpoints as a routine troubleshooting step.', 'Confirm recovery with advancing new observations on the platform, not just a successful restart or a replayed old record.'],
  ]),
  'troubleshooting/troubleshoot-collection': lesson('Troubleshooting', [
    ['Describe the symptom precisely', '“No data” can mean no source is registered, no resources were discovered, one signal is absent, or observations stopped advancing. Each has a different first check.', 'Choose one expected resource and signal. Note the last known observation and the time window used in the UI. This makes the investigation testable.'],
    ['Check visibility before changing collection', 'Confirm organization, account, environment, resource, and time filters. Remove restrictive filters one at a time. Historical data can be present even when a short recent window is empty.', 'If another view shows the data, compare its scope rather than immediately restarting collectors. An identity or filter mismatch can look like a collection outage.'],
    ['Walk from the producer to the platform', 'Confirm the source produces the signal, the collector is configured to read it, and delivery uses the intended endpoint and authorized key. Inspect safe error categories at each boundary.', 'For cloud integrations, distinguish discovery access from optional telemetry access. For an Agent, distinguish one unreadable log source from all exports failing.'],
    ['Verify and preserve evidence', 'After an approved correction, check new observations and their timestamps. Preserve queued data and checkpoints; deleting state can lose evidence and does not fix a configuration mismatch.', 'Escalate with the affected signal, collector or integration type, sanitized error, interval, and checks already performed.'],
  ]),
  'whats-new/release-notes': lesson('Reference', [
    ['Use release information that matches your platform', 'The application version and Agent version can evolve independently. A documentation page or newly visible navigation entry is not proof that a capability is enabled in every environment.', 'This documentation site does not currently maintain a verified product release feed. It therefore does not assign release dates or claim that a particular feature shipped on an invented date.'],
    ['What to review before adopting a change', 'Use the release information supplied by your platform operator to check compatibility, permissions, collection requirements, and changes in behavior. Review whether the change applies to the customer UI, backend, or installed collectors.', 'Verify a relevant customer workflow after an approved upgrade. Do not use customer documentation as a substitute for internal deployment or migration instructions.'],
    ['Keep version context in support requests', 'Include the available application or collector version and the workflow involved. If a guide differs from your UI, describe the difference rather than assuming the installation is broken.'],
  ]),
  'whats-new/latest-docs': lesson('Reference', [
    ['What this documentation revision improves', 'This revision separates explanations, practical guides, interpretation guidance, and references. The goal is to explain why a feature is useful and how to read its evidence, not repeat a generic checklist on every page.', 'The home page now directs readers to learning paths and practical questions. Notification guides include real, sanitized form screenshots and field descriptions.'],
    ['What the screenshots establish', 'Images show the actual local ASTRA application with identifying information removed. Empty telemetry views are labeled as empty states; they are not examples of successful production collection.', 'A screenshot of a connection form does not prove a third-party delivery was tested. Verify your own approved destination using the product’s test and delivery evidence.'],
    ['How to report a mismatch', 'Note the guide title, the step that differs, and the application context. Share a sanitized description with your documentation owner. Do not include secrets or unreviewed customer records.', 'Documentation changes do not deploy product changes. Use the platform’s verified release information to determine when a capability is available.'],
  ]),
};

HANDBOOK['reference/api-reference'] = { type: 'Reference', sections: [
  s('contract', 'OTLP ingestion endpoints', p('The current backend exposes OTLP over HTTP under the API prefix. Use the public HTTPS origin supplied by your platform; localhost in an example is not a suitable endpoint for a remote collector. The OpenTelemetry integration page provides the exporter base endpoint.'), t(['Signal','HTTP method and path','Required permission'], [['Metrics','POST /api/v1/otlp/v1/metrics','metrics.ingest'],['Logs','POST /api/v1/otlp/v1/logs','logs.ingest'],['Traces','POST /api/v1/otlp/v1/traces','traces.ingest']])),
  s('credentials', 'Authentication and organization scope', p('Ingestion requires a scoped API key. The authenticated key establishes organization context; a resource attribute must not be used to choose another tenant. A browser session is not a replacement for an ingestion key.'), {type:'code', language:'HTTP header', value:'Authorization: ApiKey <organization-ingest-key>'}, n('Keep the key private','The value above is a placeholder. Use your approved secret-management process and never embed a real key in a public docs page or client-side bundle.')),
  s('encoding', 'Encoding and exporter configuration', p('The current backend accepts JSON and application/x-protobuf payload handling for these endpoints. The application’s SDK examples select http/protobuf. Copy the exporter base URL from Integrations → OpenTelemetry; generic OTLP exporters append the signal path, while signal-specific settings may require the full URL.'), p('Do not append /v1/traces twice. Configure each signal pipeline you intend to export; a trace-only application example does not enable logs or metrics automatically.'), {type:'code',language:'Exporter example — placeholders only',value:'OTEL_EXPORTER_OTLP_ENDPOINT=https://<platform-host>/api/v1/otlp\nOTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf\nOTEL_SERVICE_NAME=<your-application-service>\nOTEL_EXPORTER_OTLP_HEADERS=Authorization=ApiKey%20<ingest-key>'}),
  s('response', 'Acceptance, rejection, and retries', p('Inspect the OTLP response rather than checking only HTTP 200. The response can include partialSuccess with rejectedDataPoints, rejectedLogRecords, or rejectedSpans according to the signal. A successful HTTP request is not proof that every submitted item was accepted.'), t(['Observation','Next check'],[['400 invalid payload','Check the signal schema and encoding; do not retry the same invalid payload indefinitely.'],['Authentication or permission denial','Verify key validity, organization scope, and the signal permission.'],['429 or transient server failure','Use the exporter’s bounded retry/backoff behavior and inspect delivery health.'],['Accepted request, empty view','Check resource identity, time window, filters, and which signals were actually exported.']]), p('Request-size and rate limits exist and can vary by deployment version. Batch through a supported exporter and inspect rejection details safely; do not rely on unlimited request sizes.')),
] };
HANDBOOK['reference/log-reference'] = {type:'Reference', sections:[
  s('record', 'Record fields answer different questions', p('A log record combines an event timestamp, optional observed-time context, severity, body, and attributes. Read the timestamp and source before interpreting a message. Delivery delay can make an old event appear in a newly received batch.'),t(['Field or dimension','Meaning and caution'],[['Timestamp','When the source says the event occurred; compare timezone and clock accuracy.'],['Severity','The source’s classification. Severity alone does not establish customer impact.'],['Body','The application or source message; potentially sensitive.'],['Source','The collection path, useful for distinguishing journal, file, container, or exported records.'] ])),
  s('resource','Resource identity and application context', t(['Attribute when supplied','Interpretation'],[['host.id','Host identity context; prefer this over matching a display name.'],['container.id','Exact container identity; container names can be reused.'],['service.name','Explicit application service context; not required for all host-level records.'],['service.instance.id','An application instance identifier when instrumentation supplies it.'],['cloud.*','Provider/account/region context supplied by the source.'],['trace_id / span_id','Correlation with tracing when present; not guaranteed for every log.']]),p('These are interpretation examples, not a promise that every source emits every field. Inspect the actual record before constructing a filter. A valid host-level record can have no service identity.')),
  s('filter','Build a filter from observed attributes',p('Start with a recent interval and a known source. Inspect one representative record, then narrow by attributes actually present. A filter for an absent service name can hide perfectly valid system logs.'),p('When sharing a search result, keep the organization and time range explicit. Redact log bodies and resource details according to your organization’s policy rather than assuming metadata is harmless.')),
]};
HANDBOOK['reference/permissions'] = {type:'Reference',sections:[
  s('model','Read and manage are different responsibilities',p('Permissions determine which pages and actions are available in the selected organization. A missing catalogue entry can reflect access filtering, not a missing integration. Ask an administrator to review the intended task before requesting a broad role.')),
  s('keys','Examples used by these guides',t(['Permission','Customer task'],[['agents.read / agents.manage','Inspect or manage the Host agents integration.'],['integrations.channels.read / integrations.channels.manage','Inspect or manage notification channels.'],['integrations.messaging.read / integrations.messaging.manage','Inspect or manage messaging integrations.'],['ai.read / ai.manage','Access the corresponding AI capabilities according to the current role.'],['metrics.ingest / logs.ingest / traces.ingest','Authorize the corresponding OTLP signal for a scoped key.']]),p('This is a focused list, not the full permission catalogue. The current role editor and authenticated session are the authority for the permissions available in your deployment.')),
  s('review','Resolve an unavailable action safely',p('Confirm the organization first. Identify whether the user needs to view data, change configuration, or issue a credential. Review the current role against that task and make an authorized least-privilege change.'),p('Then verify the action from the affected membership. Never use a key from another organization or a shared administrator login to work around a permission boundary.')),
]};
HANDBOOK['reference/agent-configuration'] = {type:'Reference',sections:[
  s('source','Use the configuration shipped with your Agent',p('Agent configuration is version-specific. Start from the installed version’s supported template and the options generated by Integrations → Host agents. This page explains configuration responsibilities; it is not a complete schema for every Agent release.')),
  s('areas','What each configuration area controls',t(['Area','Purpose','Review before enabling'],[['Endpoint and credentials','Where telemetry is delivered and which organization authorizes it.','HTTPS reachability and scoped key handling.'],['Metrics','Which supported measurements are collected.','Coverage, collection interval, and resource scope.'],['File and journal logs','Which records may be read.','Source selection, permissions, and sensitive content.'],['Application Health','Configured process, service, and probe observations.','Expected targets and supported lifecycle semantics.'],['Docker','Optional container evidence and logs.','Approved runtime access and source allowlists.'],['Delivery state','Buffering and resume behavior.','Storage capacity and retained queue/checkpoint preservation.']])),
  s('validate','Validate before applying',p('Use the version’s supported validation command or installer validation flow before restarting the service. A valid configuration establishes syntax and supported settings, not that every source is readable or every endpoint is reachable.'),p('After applying an authorized change, verify the affected signal independently. Do not erase delivery state, loosen filesystem permissions broadly, or grant Docker access automatically to make a failed capability appear healthy.')),
]};
HANDBOOK['reference/glossary'] = {type:'Reference',sections:[
  s('scope','Scope and identity',t(['Term','Meaning'],[['Organization','The customer access and data boundary.'],['Project / environment','Context for grouping and filtering supported resources within an organization.'],['Entity','A resource represented in ASTRA with associated identity and observations.'],['Workload','An observed system inspected through its context and available telemetry.'],['Service','Application identity supplied through supported instrumentation or explicit mapping.'],['Instance','A particular running instance of an application service.']])),
  s('evidence','Kinds of evidence',t(['Term','What it describes'],[['Metric','A measurement over time, interpreted with unit, dimensions, and aggregation.'],['Log','An individual recorded message or event with timestamp and source context.'],['Span','An instrumented unit of work within a trace.'],['Trace','Related spans representing an instrumented request or operation.'],['Runtime event','An observed state or lifecycle change with resource and source context.'],['Provenance','Information about the source or collector that produced an observation.']])),
  s('response','From evidence to response',t(['Term','Meaning'],[['Monitor','A configured evaluation of a condition.'],['Incident','A response context bringing affected systems, chronology, and evidence together.'],['Notification channel','An approved destination for supported platform updates.'],['Baseline/sample','An observation of state, not necessarily a new lifecycle transition.'],['Stale data','Observations that have not advanced recently enough for the question being asked.']]),p('Use these distinctions when reporting problems. “The source is stale” is a different claim from “the service is down,” and each requires different evidence.')),
]};

export function readingTime(guide) {
  const words = JSON.stringify(guide.sections).split(/\s+/).length;
  return `${Math.max(1, Math.ceil(words / 200))} min`;
}

// Decision aids differ by task; these are interpretation examples, not live tenant data.
HANDBOOK['infrastructure/topology'].sections.splice(2,0,s('relationships','What to ask about a relationship',t(['Observed context','Useful question','Do not conclude'],[['Hosting or resource association','Where does this workload run?','That all colocated applications share the same failure.'],['Request dependency','Which downstream operation is involved?','That the downstream service caused the error without inspecting requests.'],['Cloud context','Which account or resource boundary is relevant?','That the graph covers every resource outside collection scope.']])));
HANDBOOK['telemetry/traces'].sections.splice(2,0,s('span-example','Example: a slow checkout request',t(['Observation','Interpretation','Next evidence'],[['The root request is slow','The observed operation took longer than expected.','Compare similar requests and the user-facing symptom.'],['A child database span dominates elapsed time','Database work is a candidate contributor.','Inspect the operation and database evidence in the same interval.'],['A gap has no child span','Work may be uninstrumented or context may be missing.','Check instrumentation before declaring the gap idle.']]),n('Illustrative example','This sequence explains how to reason about a trace. It does not show measured ASTRA production traffic.')));
HANDBOOK['monitoring/first-monitor'].sections.push(s('readiness','Before you rely on this monitor',{type:'checklist',items:['The target and signal match the problem we intend to detect.','Recent data is available for the evaluation scope.','A named team owns the response.','The approved notification destination has been tested.','We know how to verify recovery without deleting evidence.']}));
HANDBOOK['monitoring/synthetics'].sections.splice(1,0,s('protocols','Select the evidence you need',t(['Probe','Answers','Does not establish'],[['DNS','Can the configured name be resolved by the probe?','That the application accepts connections.'],['TCP','Can the probe establish the configured connection?','That a complete application operation works.'],['HTTP','Does the configured endpoint satisfy the supported response check?','That every user journey works.']])));
HANDBOOK['troubleshooting/authentication'].sections.splice(1,0,s('decision','Which access problem do you have?',{type:'accordion',items:[['I cannot authenticate','Check the entered identity and the supported sign-in method. Use the approved recovery process; never share a password.'],['I can authenticate but have no active organization','Ask an administrator to review membership, organization status, and applicable plan state.'],['I can enter the organization but cannot use a feature','Review the role permission for the intended read or manage action.'],['A previously working session stopped','Check whether it expired, was revoked, or organization access changed. Do not assume the password is wrong.']]}));
HANDBOOK['costs/unit-economics'].sections.splice(1,0,s('example','Three numbers that should not be confused',t(['Measure','Question','Required context'],[['Total infrastructure spend','How much is in this cost scope?','Period and included accounts/resources.'],['Attributed spend','Which dimension receives this allocation?','Mapping policy and unallocated amounts.'],['Cost per business unit','How much spend corresponds to a unit of activity?','A valid denominator for the same period and scope.']])));
HANDBOOK['applications/services'].sections.splice(1,0,s('identity','Service, instance, and version',t(['Dimension','Illustrative value','Meaning'],[['Service','checkout-api','The application responsibility.'],['Instance','a configured instance identifier','One running instance; do not substitute an unrelated host ID.'],['Version','a release identifier','The software version reported by instrumentation.']]),p('These are examples, not naming requirements. Choose stable names that fit your application and preserve the supported environment context.')));
HANDBOOK['astra-intelligence/ask-astra'].sections.push(s('questions','Make the question easier to verify',t(['Instead of','Ask'],[['Why is everything broken?','Which observed signals changed for this workload during the incident interval?'],['Fix this service','What evidence supports the proposed cause, and what should the owner verify next?'],['Are there no errors?','Is error collection current, and what errors were observed in the selected window?']])));
HANDBOOK['dashboards-reports/dashboards'].sections.push(s('panel-review','Review a panel before sharing',{type:'checklist',items:['The title identifies the resource or operational question.','The unit and aggregation have a clear meaning.','The saved scope includes the intended resources.','Missing data is distinguishable from zero.','A teammate can explain what action, if any, the pattern suggests.']}));
HANDBOOK['troubleshooting/agent-service'].sections.push(s('symptoms','Use the symptom to choose the next check',t(['Symptom','Inspect first','Avoid'],[['Service does not start','Supported configuration validation and recent service error category.','Broad sandbox or permission changes.'],['Metrics arrive, one log source does not','Source enabled state, new records, and service-account read access.','Treating all delivery as broken.'],['All exports are stale','Endpoint, authentication, and retained delivery state.','Deleting queues or checkpoints.'],['Old records appear after recovery','Event timestamps versus newest observations.','Assuming replay proves that fresh collection works.']])));
